## WEB SCRAPING – ASSIGNMENT 4

In [29]:
#import needed libraries
from selenium import webdriver
import numpy as np
import pandas as pd
import time
import warnings
warnings.filterwarnings('ignore')

#exceptions
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
from selenium.common.exceptions import ElementNotInteractableException

###### 1. Scrape the details of most viewed videos on YouTube from Wikipedia. 

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos   
You need to find following details:
- Rank 
- Name 
- Artist 
- Upload date 
- Views

In [3]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [8]:
#scape video name
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
except StaleElementReferenceException:
    name.append('No details available')
print(len(name))

30

In [14]:
#scape rank of video
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text.replace('.',''))
except NoSuchElementException:
    rank.append('No details available')
except StaleElementReferenceException:
    rank.append('No details available')
print(len(rank))

30

In [16]:
#scape the name of uploader
Artist=[]
try:
    art=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for x in art:
        Artist.append(x.text)
except NoSuchElementException:
    Artist.append('No details available')
except StaleElementReferenceException:
    Artist.append('No details available')
print(len(Artist))

30

In [17]:
#scape upload date
date=[]
try:
    dates=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
    for x in dates:
        date.append(x.text)
except NoSuchElementException:
    date.append('-')
except StaleElementReferenceException:
    date.append('-')
print(len(date))

30

In [19]:
#scape number of views
views=[]
try:
    view=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
    for x in view:
        views.append(x.text)
except NoSuchElementException:
    views.append('-')
except StaleElementReferenceException:
    views.append('-')
print(len(views))

30

In [23]:
#make dataframe
df=pd.DataFrame()
df['Rank']=rank
df['Video Name']=name
df['Artist/Uploader Name']=Artist
df['Upload Date']=date
df['Views(Billions)']=views

In [24]:
df

,Rank,Video Name,Artist/Uploader Name,Upload Date,Views(Billions)
0,1,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.70
1,2,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.85
2,3,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.35
3,4,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.72
4,5,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.51
5,6,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.38
6,7,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.63
7,8,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.57
8,9,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.57
9,10,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.43
11,12,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.07
12,13,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.94
13,14,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.70
14,15,"""Roar""[33]",Katy Perry,"September 5, 2013",3.58
15,16,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.58
16,17,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.55
17,18,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.45
18,19,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.36
19,20,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.29
20,21,"""Faded""[39]",Alan Walker,"December 3, 2015",3.28
21,22,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.27
22,23,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.24
23,24,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.23
24,25,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.21
25,26,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.21
26,27,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.17
27,28,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.17
28,29,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.14
29,30,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.08

In [25]:
#make csv file
df.to_csv('most viewed videos on YouTube.csv')

In [26]:
#close the driver
driver.close()

##### 2. Scrape the details team India’s international fixtures from bcci.tv. 
Url = https://www.bcci.tv/. 

You need to find following details:
- Match title (I.e. 1st ODI) 
- Series 
- Place 
- Date 
- Time

In [27]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get('https://www.bcci.tv/')

In [30]:
#From bcci.tv home page you have reach to the international fixture page
try:
    fixtures=driver.find_element_by_xpath('/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))

In [32]:
#scrape Series
Series=[]
try:
    series=driver.find_elements_by_xpath('//div[@class="fixture-card-top"]/h5[2]/span[1]')
    for x in series:
        Series.append(x.text)
except NoSuchElementException:
    Series.append('-')
except StaleElementReferenceException:
    Series.append('-')
print(len(Series),Series)

5 ['SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022', 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022', 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022', 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022', 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022']

In [34]:
#scape the match title
match=[]
try:
    matchs=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
    for x in matchs:
        match.append(x.text.replace(' -',''))
except NoSuchElementException:
    match.append('-')
except StaleElementReferenceException:
    match.append('-')
print(len(match),match)

5 ['1st T20I', '2nd T20I', '3rd T20I', '4th T20I', '5th T20I']

In [46]:
#scape the place
place=[]
try:
    places=driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]')
    for x in places:
        place.append(x.text)
except NoSuchElementException:
    place.append('-')
except StaleElementReferenceException:
    place.append('-')
print(len(place),place)

5 ['1st T20I - Arun Jaitley Stadium, Delhi', '2nd T20I - Barabati Stadium, Cuttack', '3rd T20I - Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam', '4th T20I - Saurashtra Cricket Association Stadium, Rajkot', '5th T20I - M Chinnaswamy Stadium, Bengaluru']

In [50]:
#scape the date
date=[]
try:
    dates=driver.find_elements_by_xpath('//div[@class="match-card-left match-schedule"]/h5')
    for x in dates:
        date.append(x.text)
except NoSuchElementException:
    date.append('-')
except StaleElementReferenceException:
    date.append('-')
print(len(date),date)

5 ['9 JUN 2022', '12 JUN 2022', '14 JUN 2022', '17 JUN 2022', '19 JUN 2022']

In [52]:
#scape the time
time=[]
try:
    tim=driver.find_elements_by_xpath('//div[@class="match-card-right match-schedule "]/h5[1]')
    for x in tim:
        time.append(x.text)
except NoSuchElementException:
    time.append('-')
except StaleElementReferenceException:
    time.append('-')
print(len(time),time)

5 ['7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST']

In [53]:
#make dataframe
df=pd.DataFrame()
df['Match Title']=match
df['Series']=Series
df['Place']=place
df['Match Date']=date
df['Match Time']=time
df

,Match Title,Series,Place,Match Date,Match Time
0,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"1st T20I - Arun Jaitley Stadium, Delhi",9 JUN 2022,7:00 PM IST
1,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"2nd T20I - Barabati Stadium, Cuttack",12 JUN 2022,7:00 PM IST
2,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,3rd T20I - Dr YS Rajasekhara Reddy ACA-VDCA Cr...,14 JUN 2022,7:00 PM IST
3,4th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,4th T20I - Saurashtra Cricket Association Stad...,17 JUN 2022,7:00 PM IST
4,5th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"5th T20I - M Chinnaswamy Stadium, Bengaluru",19 JUN 2022,7:00 PM IST

In [54]:
#make csv
df.to_csv('international fixtures.csv')

In [55]:
#close driver
driver.close()

##### 3. Scrape the details of selenium exception from guru99.com. 
Url = https://www.guru99.com/ 

You need to find following details:
- Name 
- Description

In [64]:
url='https://www.guru99.com/'

In [65]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [67]:
selenium_link=driver.find_element_by_xpath('//ul[@class="menu1"][1]/li[3]/a')
try:
    selenium_link.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))

In [69]:
selenium_link=driver.find_element_by_xpath('//table[@class="table"][5]/tbody/tr[34]/td[1]/a')
try:
    selenium_link.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))

In [70]:
#scrape the Exception name
name=[]
try:
    names=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
print(len(name),name)

41 ['ElementNotVisibleException', 'ElementNotSelectableException', 'NoSuchElementException', 'NoSuchFrameException', 'NoAlertPresentException', 'NoSuchWindowException', 'StaleElementReferenceException', 'SessionNotFoundException', 'TimeoutException', 'WebDriverException', 'ConnectionClosedException', 'ElementClickInterceptedException', 'ElementNotInteractableException', 'ErrorInResponseException', 'ErrorHandler.UnknownServerException', 'ImeActivationFailedException', 'ImeNotAvailableException', 'InsecureCertificateException', 'InvalidArgumentException', 'InvalidCookieDomainException', 'InvalidCoordinatesException', 'InvalidElementStateExceptio', 'InvalidSessionIdException', 'InvalidSwitchToTargetException', 'JavascriptException', 'JsonException', 'NoSuchAttributeException', 'MoveTargetOutOfBoundsException', 'NoSuchContextException', 'NoSuchCookieException', 'NotFoundException', 'RemoteDriverServerException', 'ScreenshotException', 'SessionNotCreatedException', 'UnableToSetCookieException', 'UnexpectedTagNameException', 'UnhandledAlertException', 'UnexpectedAlertPresentException', 'UnknownMethodException', 'UnreachableBrowserException', 'UnsupportedCommandException']

In [71]:
#scrape the Exception Description
description=[]
try:
    des=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
    for x in des:
        description.append(x.text)
except NoSuchElementException:
    description.append('-')
except StaleElementReferenceException:
    description.append('-')
print(len(description),description)

41 ['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.', 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.', 'This Exception occurs if an element could not be found.', 'This Exception occurs if the frame target to be switched to does not exist.', 'This Exception occurs when you switch to no presented alert.', 'This Exception occurs if the window target to be switch does not exist.', 'This Selenium exception occurs happens when the web element is detached from the current DOM.', 'The WebDriver is acting after you quit the browser.', 'Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.', 'This Exception takes place when the WebDriver is acting right after you close the browser.', 'This type of Exception takes place when there is a disconnection in the driver.', 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.', 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.', 'This happens while interacting with the Firefox extension or the remote driver server.', 'Exception is used as a placeholder in case if the server returns an error without a stack trace.', 'This expectation will occur when IME engine activation has failed.', 'It takes place when IME support is unavailable.', 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.', 'It occurs when an argument does not belong to the expected type.', 'This happens when you try to add a cookie under a different domain instead of current URL.', 'This type of Exception matches an interacting operation that is not valid.', 'It occurs when command can’t be finished when the element is invalid.', 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.', 'This occurs when the frame or window target to be switched does not exist.', 'This issue occurs while executing JavaScript given by the user.', 'It occurs when you afford to get the session when the session is not created.', 'This kind of Exception occurs when the attribute of an element could not be found.', 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.', 'ContextAware does mobile device testing.', 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.', 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.', 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.', 'It is not possible to capture a screen.', 'It happens when a new session could not be successfully created.', 'This occurs if a driver is unable to set a cookie.', 'Happens if a support class did not get a web element as expected.', 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.', 'It occurs when there is the appearance of an unexpected alert.', 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.', 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.', 'This occurs when remote WebDriver does n’t send valid commands as expected.']

In [72]:
#make dataframe
df=pd.DataFrame()
df['Exception Name']=name
df['Description']=description
df

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [73]:
#make csv
df.to_csv('Exception Handling.csv')

In [75]:
#close driver
driver.close()

##### 4. Scrape the details of State-wise GDP of India from statisticstime.com. 
Url = http://statisticstimes.com/ 

You have to find following details: 
- Rank 
- State
- GSDP(18-19) 
- GSDP(17-18)
- Share(2017)
- GDP($ billion)

In [76]:
url='http://statisticstimes.com/'

In [77]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [80]:
country_link=driver.find_element_by_xpath('//div[@class="navbar"]/div[2]/div[1]/a[3]')
try:
    country_link.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(country_link.get_attribute('href'))

In [81]:
link=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
link.click()

In [85]:
#scrape rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[1]')
    for x in ranks:
        rank.append(x.text)
except NoSuchElementException:
    rank.append('-')
except StaleElementReferenceException:
    rank.append('-')
rank=rank[0:33]
print(len(rank),rank)

33 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

In [86]:
#scrape state name
state=[]
try:
    names=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[2]')
    for x in names:
        state.append(x.text)
except NoSuchElementException:
    state.append('-')
except StaleElementReferenceException:
    state.append('-')
state=state[0:33]
print(len(state),state)

33 ['Maharashtra', 'Tamil Nadu', 'Uttar Pradesh', 'Gujarat', 'Karnataka', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Punjab', 'Odisha', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Nagaland', 'Arunachal Pradesh', 'Mizoram', 'Andaman & Nicobar Islands']

In [87]:
#scrape GSDP(18-19) of state 
GSDP_18_19=[]
try:
    gsdp_18_19=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[4]')
    for x in gsdp_18_19:
        GSDP_18_19.append(x.text)
except NoSuchElementException:
    GSDP_18_19.append('-')
except StaleElementReferenceException:
    GSDP_18_19.append('-')
GSDP_18_19=GSDP_18_19[0:33]
print(len(GSDP_18_19),GSDP_18_19)

33 ['2,632,792', '1,630,208', '1,584,764', '1,502,899', '1,493,127', '1,089,898', '942,586', '862,957', '861,031', '809,592', '781,653', '774,870', '734,163', '530,363', '526,376', '487,805', '315,881', '304,063', '297,204', '245,895', '155,956', '153,845', '73,170', '49,845', '42,114', '34,433', '33,481', '28,723', '27,870', '27,283', '24,603', '22,287', '-']

In [89]:
#scrape GSDP(19-20) of state 
GSDP_19_20=[]
try:
    gsdp_19_20=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[3]')
    for x in gsdp_19_20:
        GSDP_19_20.append(x.text)
except NoSuchElementException:
    GSDP_19_20.append('-')
except StaleElementReferenceException:
    GSDP_19_20.append('-')
GSDP_19_20=GSDP_19_20[0:33]
print(len(GSDP_19_20),GSDP_19_20)

33 ['-', '1,845,853', '1,687,818', '-', '1,631,977', '1,253,832', '1,020,989', '972,782', '969,604', '906,672', '-', '856,112', '831,610', '611,804', '574,760', '521,275', '-', '329,180', '328,598', '-', '-', '165,472', '80,449', '55,984', '-', '38,253', '36,572', '32,496', '31,790', '-', '-', '26,503', '-']

In [90]:
#scrape Share(2019) of state 
GSDP_19=[]
try:
    gsdp_19=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[5]')
    for x in gsdp_19:
        GSDP_19.append(x.text)
except NoSuchElementException:
    GSDP_19.append('-')
except StaleElementReferenceException:
    GSDP_19.append('-')
GSDP_19=GSDP_19[0:33]
print(len(GSDP_19),GSDP_19)

33 ['13.94%', '8.63%', '8.39%', '7.96%', '7.91%', '5.77%', '4.99%', '4.57%', '4.56%', '4.29%', '4.14%', '4.10%', '3.89%', '2.81%', '2.79%', '2.58%', '1.67%', '1.61%', '1.57%', '1.30%', '0.83%', '0.81%', '0.39%', '0.26%', '0.22%', '0.18%', '0.18%', '0.15%', '0.15%', '0.14%', '0.13%', '0.12%', '-']

In [92]:
#scrape GDP($ billion) of state 
GDP=[]
try:
    gsdp=driver.find_elements_by_xpath('//table[@class="display dataTable"][1]/tbody/tr/td[6]')
    for x in gsdp:
        GDP.append(x.text)
except NoSuchElementException:
    GDP.append('-')
except StaleElementReferenceException:
    GDP.append('-')
GDP=GDP[0:33]
print(len(GDP),GDP)

33 ['399.921', '247.629', '240.726', '228.290', '226.806', '165.556', '143.179', '131.083', '130.791', '122.977', '118.733', '117.703', '111.519', '80.562', '79.957', '74.098', '47.982', '46.187', '45.145', '37.351', '23.690', '23.369', '11.115', '7.571', '6.397', '5.230', '5.086', '4.363', '4.233', '4.144', '3.737', '3.385', '-']

In [93]:
#make dataframe
df=pd.DataFrame()
df['Rank']=rank
df['State Name']=state
df['State GSDP(18-19)']=GSDP_18_19
df['State GSDP(19_20)']=GSDP_19_20
df['State Share(2019)']=GSDP_19
df['State GDP($Billions)']=GDP
df

,Rank,State Name,State GSDP(18-19),State GSDP(19_20),State Share(2019),State GDP($Billions)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [94]:
#make csv file
df.to_csv('State GDP.csv')

In [95]:
#close the driver
driver.close()

##### 5. Scrape the details of trending repositories on Github.com. 
Url  = https://github.com/

You have to find the following details:
- Repository title 
- Repository description 
- Contributors count

In [96]:
url='https://github.com/'

In [97]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [110]:
trending_link=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
try:
    trending_link.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(trending_link.get_attribute('href'))

In [112]:
#Scrape Repository Title
title=[]
try:
    titles=driver.find_elements_by_xpath('//span[@class="text-normal"]')
    for x in titles:
        title.append(x.text.replace(' /',''))
except NoSuchElementException:
    title.append('-')
except StaleElementReferenceException:
    title.append('-')
print(len(title),title)

25 ['rocboss', 'zijie0', 'Grasscutters', 'neondatabase', 'trekhleb', 'requarks', 'smartcontractkit', 'hasinhayder', 'Asabeneh', 'livebud', 'TomSchimansky', 'ripienaar', 'helix-editor', 'Cveinnt', 'BishopFox', 'cotes2020', 'topjohnwu', 'eludadev', 'neovim', 'skyline-emu', 'ageitgey', 'qmk', 'zju3dv', 'yangshun', 'coolsnowwolf']

In [113]:
#scrape Repository Description
description=[]
try:
    descri=driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for x in descri:
        description.append(x.text)
except NoSuchElementException:
    description.append('-')
except StaleElementReferenceException:
    description.append('-')
print(len(description),description)

25 ['🔥A artistic "twitter like" community built on gin+zinc+vue+ts 清新文艺微社区', '健康学习到150岁 - 人体系统调优不完全指南', 'A server software reimplementation for a certain anime game.', 'The serverless open source alternative to AWS Aurora Postgres.', '📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings', 'Wiki.js | A modern and powerful wiki app built on Node.js', 'Learn Blockchain, Solidity, and Full Stack Web3 Development with Javascript', 'Hydra is a zero-config API boilerplate with Laravel 9x + Laravel Sanctum that comes with an excellent user and role management API out of the box', '30 Days of React challenge is a step by step guide to learn React in 30 days. It requires HTML, CSS, and JavaScript knowledge. You should be comfortable with JavaScript before you start to React. If you are not comfortable with JavaScript check out 30DaysOfJavaScript. This is a continuation of 30 Days Of JS. This challenge may take more than 100…', 'The Full-Stack Web Framework for Go', 'A modern and customizable python UI-library based on Tkinter', 'A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev', 'A post-modern modal text editor.', '💻 Build terminal styled websites in minutes!', 'Adversary Emulation Framework', 'A minimal, responsive, and powerful Jekyll theme for presenting professional writing.', 'The Magic Mask for Android', '100 Modern CSS Buttons, Free And Royalty Free.', 'Vim-fork focused on extensibility and usability', 'Run Nintendo Switch homebrew & games on your Android device!', "The world's simplest facial recognition api for Python and the command line", 'Open-source keyboard firmware for Atmel AVR and Arm USB families', 'Code for "OnePose: One-Shot Object Pose Estimation without CAD Models", CVPR 2022', '💯 Curated interview preparation materials for busy engineers', "Lean's OpenWrt source"]

In [115]:
#scarpe Contributors count
contributor=[]
try:
    contributors=driver.find_elements_by_xpath('//div[@class="f6 color-fg-muted mt-2"]/a[1]')
    for x in contributors:
        contributor.append(x.text)
except NoSuchElementException:
    contributor.append('-')
except StaleElementReferenceException:
    contributor.append('-')
print(len(contributor),contributor)

25 ['1,051', '3,583', '7,620', '1,912', '142,745', '17,205', '1,179', '463', '12,015', '2,711', '1,394', '55,740', '9,336', '2,862', '2,740', '2,194', '26,404', '1,107', '54,009', '7,961', '44,676', '12,479', '377', '71,128', '21,498']

In [117]:
#make dataframe
df=pd.DataFrame()
df['Repository Title']=title
df['Repository Description']=description
df['Repository Contributors']=contributor
df

,Repository Title,Repository Description,Repository Contributors
0,rocboss,"🔥A artistic ""twitter like"" community built on ...","1,051"
1,zijie0,健康学习到150岁 - 人体系统调优不完全指南,"3,583"
2,Grasscutters,A server software reimplementation for a certa...,"7,620"
3,neondatabase,The serverless open source alternative to AWS ...,"1,912"
4,trekhleb,📝 Algorithms and data structures implemented i...,"142,745"
5,requarks,Wiki.js | A modern and powerful wiki app built...,"17,205"
6,smartcontractkit,"Learn Blockchain, Solidity, and Full Stack Web...","1,179"
7,hasinhayder,Hydra is a zero-config API boilerplate with La...,463
8,Asabeneh,30 Days of React challenge is a step by step g...,"12,015"
9,livebud,The Full-Stack Web Framework for Go,"2,711"
10,TomSchimansky,A modern and customizable python UI-library ba...,"1,394"
11,ripienaar,"A list of SaaS, PaaS and IaaS offerings that h...","55,740"
12,helix-editor,A post-modern modal text editor.,"9,336"
13,Cveinnt,💻 Build terminal styled websites in minutes!,"2,862"
14,BishopFox,Adversary Emulation Framework,"2,740"
15,cotes2020,"A minimal, responsive, and powerful Jekyll the...","2,194"
16,topjohnwu,The Magic Mask for Android,"26,404"
17,eludadev,"100 Modern CSS Buttons, Free And Royalty Free.","1,107"
18,neovim,Vim-fork focused on extensibility and usability,"54,009"
19,skyline-emu,Run Nintendo Switch homebrew & games on your A...,"7,961"
20,ageitgey,The world's simplest facial recognition api fo...,"44,676"
21,qmk,Open-source keyboard firmware for Atmel AVR an...,"12,479"
22,zju3dv,"Code for ""OnePose: One-Shot Object Pose Estima...",377
23,yangshun,💯 Curated interview preparation materials for ...,"71,128"
24,coolsnowwolf,Lean's OpenWrt source,"21,498"

In [118]:
#make csv file
df.to_csv('trending repositories.csv')

In [119]:
#close driver
driver.close()

##### 6. Scrape the details of top 100 songs on billiboard.com. 
Url =  https://www.billboard.com/

You have to find the following details: 
- Song name 
- Artist name 
- Last week rank 
- Peak rank 
- Weeks on board

In [120]:
url='https://www.billboard.com/'

In [121]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [122]:
#open charts
charts=driver.find_element_by_xpath('/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
try:
    charts.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(charts.get_attribute('href'))

In [123]:
#open Hot 100 page
hot=driver.find_element_by_xpath('/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
try:
    hot.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(hot.get_attribute('href'))

In [136]:
#scrape song name
name=[]
try:
    names=driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]/ul/li/h3')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
print(len(name),name)

100 ['First Class', 'As It Was', 'N95', 'Wait For U', 'Die Hard', 'You Proof', 'Silent Hill', 'United In Grief', 'About Damn Time', 'Big Energy', 'Father Time', 'Heat Waves', 'Rich Spirit', 'Me Porto Bonito', 'Moscow Mule', 'We Cry Together', 'Enemy', 'Titi Me Pregunto', 'Worldwide Steppers', 'Count Me Out', 'Stay', 'Purple Hearts', 'Savior', 'Woman', 'Ghost', 'Despues de La Playa', 'Party', 'Wasted On You', 'Cooped Up', 'Bad Habits', 'Puffin On Zootiez', 'Super Gremlin', 'Rich (Interlude)', 'Thats What I Want', 'Provenza', 'Boyfriend', 'Shivers', 'Cold Heart (PNAU Remix)', 'Bam Bam', 'Mr. Morale', 'Crown', 'Numb Little Bug', "'Til You Can't", 'MAMIII', 'Sweetest Pie', 'AA', 'Auntie Diaries', 'Trouble With A Heartbreak', 'Ojitos Lindos', 'Thought You Should Know', 'Savior (Interlude)', 'Tarot', 'Un Ratito', "Doin' This", 'Mirror', 'Take My Name', 'Thousand Miles', 'To The Moon!', 'Mother I Sober', 'In A Minute', 'Yo No Soy Celoso', 'Damn Strait', 'Dua Lipa', "She's All I Wanna Be", 'Efecto', "When You're Gone", 'Get Into It (Yuh)', 'Freaky Deaky', 'Neverita', '2step', 'Never Say Never', 'La Corriente', 'What Happened To Virgil', 'Right On', 'Something In The Orange', 'Slow Down Summer', 'The Heart Part 5', 'Churchill Downs', 'Love You Better', "I'm On One", 'Andrea', 'Never Wanted To Be That Girl', 'Dos Mil 16', 'Flower Shops', 'Aguacero', 'If I Was A Cowboy', 'Otro Atardecer', 'Un Coco', 'El Apagon', 'Pushin P', 'Me Or Sum', 'Fall In Love', '712PM', "Don't Think Jesus", 'No Love', 'The Motto', 'Me Fui de Vacaciones', 'Hold My Hand', 'Ensename A Bailar', 'Flowers']

In [133]:
#scrape Artist name
artist=[]
try:
    artists=driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]/ul/li[1]/span[1]')
    for x in artists:
        artist.append(x.text)
except NoSuchElementException:
    artist.append('-')
except StaleElementReferenceException:
    artist.append('-')
print(len(artist),artist)

100 ['Jack Harlow', 'Harry Styles', 'Kendrick Lamar', 'Future Featuring Drake & Tems', 'Kendrick Lamar, Blxst & Amanda Reifer', 'Morgan Wallen', 'Kendrick Lamar & Kodak Black', 'Kendrick Lamar', 'Lizzo', 'Latto', 'Kendrick Lamar Featuring Sampha', 'Glass Animals', 'Kendrick Lamar', 'Bad Bunny & Chencho Corleone', 'Bad Bunny', 'Kendrick Lamar & Taylour Paige', 'Imagine Dragons X JID', 'Bad Bunny', 'Kendrick Lamar', 'Kendrick Lamar', 'The Kid LAROI & Justin Bieber', 'Kendrick Lamar, Summer Walker & Ghostface Killah', 'Kendrick Lamar, Baby Keem, & Sam Dew', 'Doja Cat', 'Justin Bieber', 'Bad Bunny', 'Bad Bunny & Rauw Alejandro', 'Morgan Wallen', 'Post Malone Featuring Roddy Ricch', 'Ed Sheeran', 'Future', 'Kodak Black', 'Kendrick Lamar', 'Lil Nas X', 'Karol G', 'Dove Cameron', 'Ed Sheeran', 'Elton John & Dua Lipa', 'Camila Cabello Featuring Ed Sheeran', 'Kendrick Lamar & Tanna Leone', 'Kendrick Lamar', 'Em Beihold', 'Cody Johnson', 'Becky G X Karol G', 'Megan Thee Stallion & Dua Lipa', 'Walker Hayes', 'Kendrick Lamar', 'Jason Aldean', 'Bad Bunny & Bomba Estereo', 'Morgan Wallen', 'Kendrick Lamar', 'Bad Bunny & Jhay Cortez', 'Bad Bunny', 'Luke Combs', 'Kendrick Lamar', 'Parmalee', 'The Kid LAROI', 'JNR CHOI & Sam Tompkins', 'Kendrick Lamar Featuring Beth Gibbons', 'Lil Baby', 'Bad Bunny', 'Scotty McCreery', 'Jack Harlow', 'Tate McRae', 'Bad Bunny', 'Shawn Mendes', 'Doja Cat', 'Tyga X Doja Cat', 'Bad Bunny', 'Ed Sheeran Featuring Lil Baby', 'Cole Swindell / Lainey Wilson', 'Bad Bunny & Tony Dize', 'Lil Durk Featuring Gunna', 'Lil Baby', 'Zach Bryan', 'Thomas Rhett', 'Kendrick Lamar', 'Jack Harlow Featuring Drake', 'Future', 'Future Featuring Drake', 'Bad Bunny & Buscabulla', 'Carly Pearce & Ashley McBryde', 'Bad Bunny', 'ERNEST Featuring Morgan Wallen', 'Bad Bunny', 'Miranda Lambert', 'Bad Bunny & The Marias', 'Bad Bunny', 'Bad Bunny', 'Gunna & Future Featuring Young Thug', 'Nardo Wick, Lil Baby & Future', 'Bailey Zimmerman', 'Future', 'Morgan Wallen', 'Summer Walker & SZA', 'Tiesto & Ava Max', 'Bad Bunny', 'Lady Gaga', 'Bad Bunny', 'Lauren Spencer-Smith']

In [129]:
#scrape Last week rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]/ul/li[4]/span')
    for x in ranks:
        rank.append(x.text)
except NoSuchElementException:
    rank.append('-')
except StaleElementReferenceException:
    rank.append('-')
print(len(rank),rank)

100 ['1', '2', '-', '3', '-', '-', '-', '-', '9', '8', '-', '7', '-', '10', '4', '-', '11', '5', '-', '-', '13', '-', '-', '20', '17', '6', '14', '33', '-', '24', '19', '25', '-', '28', '27', '35', '29', '30', '36', '-', '-', '43', '37', '38', '39', '40', '-', '48', '26', '12', '-', '18', '16', '52', '-', '66', '58', '57', '-', '53', '22', '71', '21', '68', '34', '72', '81', '76', '31', '75', '67', '32', '78', '69', '77', '83', '15', '23', '61', '63', '51', '80', '45', '90', '44', '73', '49', '56', '54', '89', '91', '-', '64', '85', '-', '95', '59', '82', '60', '93']

In [130]:
#scrape Peak rank
peak=[]
try:
    peaks=driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]/ul/li[5]/span')
    for x in peaks:
        peak.append(x.text)
except NoSuchElementException:
    peak.append('-')
except StaleElementReferenceException:
    peak.append('-')
print(len(peak),peak)

100 ['1', '1', '3', '1', '5', '6', '7', '8', '9', '3', '11', '1', '13', '10', '4', '16', '5', '5', '19', '20', '1', '22', '23', '7', '5', '6', '14', '9', '29', '2', '4', '3', '33', '8', '25', '31', '4', '7', '21', '40', '41', '37', '18', '15', '15', '28', '47', '33', '26', '12', '51', '18', '16', '26', '55', '56', '15', '38', '59', '14', '22', '62', '21', '44', '34', '38', '67', '43', '31', '51', '27', '32', '22', '13', '55', '43', '15', '23', '12', '11', '51', '63', '45', '64', '44', '53', '49', '56', '54', '7', '58', '91', '8', '7', '13', '42', '59', '82', '60', '55']

In [131]:
#scrape Weeks on board
board=[]
try:
    boards=driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]/ul/li[6]/span')
    for x in boards:
        board.append(x.text)
except NoSuchElementException:
    board.append('-')
except StaleElementReferenceException:
    board.append('-')
print(len(board),board)

100 ['6', '7', '1', '3', '1', '1', '1', '1', '5', '30', '1', '70', '1', '2', '2', '1', '26', '2', '1', '1', '45', '1', '1', '42', '34', '2', '2', '27', '1', '47', '3', '28', '1', '35', '4', '14', '36', '37', '11', '1', '1', '16', '32', '14', '10', '19', '1', '9', '2', '2', '1', '2', '2', '23', '1', '7', '4', '12', '1', '6', '2', '7', '2', '15', '2', '7', '24', '12', '2', '4', '18', '2', '10', '6', '4', '13', '2', '2', '3', '3', '2', '19', '2', '17', '2', '16', '2', '2', '2', '19', '19', '3', '3', '5', '19', '16', '2', '2', '2', '5']

In [138]:
#make dataframe
df=pd.DataFrame()
df['Song name']=name
df['Artist name']=artist
df['Last week rank']=rank
df['Peak rank']=peak
df['Weeks on board']=board
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,First Class,Jack Harlow,1,1,6
1,As It Was,Harry Styles,2,1,7
2,N95,Kendrick Lamar,-,3,1
3,Wait For U,Future Featuring Drake & Tems,3,1,3
4,Die Hard,"Kendrick Lamar, Blxst & Amanda Reifer",-,5,1
...,...,...,...,...,...
95,The Motto,Tiesto & Ava Max,95,42,16
96,Me Fui de Vacaciones,Bad Bunny,59,59,2
97,Hold My Hand,Lady Gaga,82,82,2
98,Ensename A Bailar,Bad Bunny,60,60,2
99,Flowers,Lauren Spencer-Smith,93,55,5

In [139]:
#make csv file
df.to_csv('top 100 songs on billiboard.csv')

In [140]:
#close the driver
driver.close()

##### 7. Scrape the details of Data science recruiters from naukri.com. 
Url = https://www.naukri.com/ 

You have to find the following details:
- Name
- Designation
- Company
- Skills they hire for 
- Location

In [150]:
url='https://www.naukri.com/hr-recruiters-consultants'

In [151]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [167]:
#scrape the names of recruiters
name=[]
try:
    names=driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
#removing empty data(rows)
name=name[0:24]
print(len(name),name)

24 ['Santhosh Kumar', 'Gauri Bhosle', 'CodeFlies', 'Surendra R', 'Sanghvi', 'Neha Pandey', 'Vinita Raut', 'BALA Sakthivelmuthu', 'rohit sharma', 'Charu Saini', 'Cameo', 'Mr.Durjay', 'Prarit Gupta', 'Raghu Hrexecutive', 'Take jobs', 'iNFIN Technologies', 'Punit Kumar Bhidodiya', 'Ishan Ahmed', 'Sreekanth Menon', 'Abhishek', 'TechCube IT Services Pvt Ltd', 'Fatte Chand Soni', 'Koustav Bose', 'Vaishambi Saxena']

In [166]:
#scrape designations
designation=[]
try:
    designations=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
    for x in designations:
        designation.append(x.text)
except NoSuchElementException:
    designation.append('-')
except StaleElementReferenceException:
    designation.append('-')
#removing empty data(row)
designation=designation[0:24]
print(len(designation),designation)

24 ['Associate Manager Human Resources', 'Human Resources', 'Human Resources', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Human Resource Manager', 'Human Resource manager', 'Human Resources', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Generalist', 'human resource manager', 'Human Resources']

In [165]:
#scrape company name
company=[]
try:
    com=driver.find_elements_by_xpath('//small[@class="ellipsis"]')
    for x in com[0:68:2]:
        company.append(x.text)
except NoSuchElementException:
    company.append('-')
except StaleElementReferenceException:
    company.append('-')
#removing empty data
company=company[0:24]
print(len(company),company)

24 ['Maveric Systems', 'TCRC', 'CodeFlies', 'DSR Design & Engineering Solutions', 'Primacy Systems Pvt Ltd', 'Ingenious E-Brain Solutions Private Limited', 'Xpansion HR Solutions Private Limited', 'E Vel', 'Bestead lifesciences pvt ltd', 'OESPL PVT LTD', 'Cameo Corporate Services', 'Hotel Chitvan', 'HMS Relations Management', 'IQs soft', 'Take Jobs', 'Infin Software Technologies Pvt. Ltd', 'Exatip Technologies', 'Jute Wonders Unlimited', 'Sterlite Technologies Ltd. Elitecore', 'Infosys Technology', 'TechCube IT Services Pvt Ltd', 'Tetraskelion Softwares (P) Ltd', 'KKR BOSE DESIGN SERVICES PVT LTD', '22Feet Tribal Worldwide (DDB Worldwide)']

In [164]:
#scrape the location
location=[]
try:
    locations=driver.find_elements_by_xpath('//small[@class="ellipsis"]')
    for x in locations[1:68:2]:
        location.append(x.text)
except NoSuchElementException:
    location.append('-')
except StaleElementReferenceException:
    location.append('-')
#removing empty data
location=location[0:24]
print(len(location),location)

24 ['Chennai', 'Mumbai', 'Noida', 'Hyderabad / Secunderabad', 'Ahmedabad', 'Gurgaon', 'Pune', 'Madurai', 'Delhi', 'Noida', 'Chennai', 'Ajmer', 'Delhi', 'Bengaluru / Bangalore', 'Delhi', 'Chandigarh', 'Indore', 'Delhi', 'Ahmedabad', 'Hyderabad / Secunderabad', 'Mohali', 'Jaipur', 'Mumbai', 'Bengaluru / Bangalore']

In [162]:
#scrape the Skills they hire for
skills=[]
try:
    skill=driver.find_elements_by_xpath('//div[@class="hireSec"]')
    for x in skill:
        skills.append(x.text)
except NoSuchElementException:
    skills.append('-')
except StaleElementReferenceException:
    skills.append('-')
print(len(skills),skills)

24 ['It Recruitment, Campus Recruitment, Campus Hiring, Software Testing', 'Operation Executive, Jr. Chemist/ Chemist, Audit, Chemist, Operation Coordination, Documentation, Typist, Data Entry, Operation, Inspection, Survey, Analysis', 'Email Marketing, Communication, Online Lead Generation, Online Marketing, Lead Generation, php, Front End, Web Technologies, Web Services, Web Application', 'Design Engineering, AutoCAD, Solid Works', 'Marketing, Sales, Plastic, Aluminium, Metal, Sheet Metal, Export Import, Import, Export, Steel, Business Development, Market Research, Metallurgy', 'B.tech, Operations, Business Development, Business Analysis, Business Intelligence, Business Research, Market Research, Ipr', 'Bde, Accounting, Education Counseling, Sales, Inside Sales, Telecalling, International Bpo, International Call Center', 'Html, Css, Javascript, Ui Development, Java, Android, Ios, Liferay Developer, Sfdc, Cloud Fusion, Atg Developer', 'Area Sales, Sales Executive Activities, Pharmaceutical Sales, Medical, Sales Growth, Pharma, Marketing, Selling Skills, Cost Benefit Analysis', 'Marketing, Civil Construction, Project Management, Marketing Communication, Business Development, Legal Compliance, Commercial Leasing, Lead Generation', 'Latex, Paginator, Tex', 'Marketing, Digital Marketing, Google Adwords, Seo Analysis, Revenue Management, Online Marketing', 'Counter Sales, Sales', 'Java/J2ee ( Core Java, Struts, Hibernate, Servlets, JSP, Spring), .Net ( C# asp.net, Vb.net, Sql Server ), Testing tools &ndash;Manual / Automation ( QTP', 'tally, Bank Reconciliation, billing, electricals, Cable Laying, Fault Finding, Team Leading, Back Office, Personal Loans, operations, design', 'Technical, PHP, Web Development, Web Technologies, Wordpress, Javascript, HTML, OSCommerce, Codeigniter, JQuery, CSS, Facebook, Seo, Smo, Smm, Search Engine', 'Software Development, Business Development', 'Back Office', 'C++, Java/j2ee, C, Networking, Radius, Diameter, Aaa, Testing, Billing, Mediation, Charging, Rating, Policy Control, Provisioning, Oss/bss, Core', 'Sap Abap, Sap Basis, Sap Fico, Sap Bi, java, Core Java, mongodb, selenium, Automation Testing, Manual Testing, Etl Testing, Oracle Dba, .net, networking', 'Skills- Technical Troubleshooting / Sales / Up-Selling / Order Processing / Customer Services / Contact Center Account Management - Roles- Representatives /', '.Net, Java, PHP, Android, Testing, IOS, Web and Graphic, UI, SAP, Quality Assurance / Testing, Manual Testing, Software Testing, Web Applications, Web', 'Ravit', 'Magento, PHP, Content, Design, DotNet, BD']

In [168]:
#make dataframe
df=pd.DataFrame()
df['Recruiter Name']=name
df['Designation']=designation
df['Company']=company
df['Skills they hire for']=skills
df['Location']=location
df

,Recruiter Name,Designation,Company,Skills they hire for,Location
0,Santhosh Kumar,Associate Manager Human Resources,Maveric Systems,"It Recruitment, Campus Recruitment, Campus Hir...",Chennai
1,Gauri Bhosle,Human Resources,TCRC,"Operation Executive, Jr. Chemist/ Chemist, Aud...",Mumbai
2,CodeFlies,Human Resources,CodeFlies,"Email Marketing, Communication, Online Lead Ge...",Noida
3,Surendra R,Company Recruiter,DSR Design & Engineering Solutions,"Design Engineering, AutoCAD, Solid Works",Hyderabad / Secunderabad
4,Sanghvi,Company Recruiter,Primacy Systems Pvt Ltd,"Marketing, Sales, Plastic, Aluminium, Metal, S...",Ahmedabad
5,Neha Pandey,Company Recruiter,Ingenious E-Brain Solutions Private Limited,"B.tech, Operations, Business Development, Busi...",Gurgaon
6,Vinita Raut,Company Recruiter,Xpansion HR Solutions Private Limited,"Bde, Accounting, Education Counseling, Sales, ...",Pune
7,BALA Sakthivelmuthu,Company Recruiter,E Vel,"Html, Css, Javascript, Ui Development, Java, A...",Madurai
8,rohit sharma,Company Recruiter,Bestead lifesciences pvt ltd,"Area Sales, Sales Executive Activities, Pharma...",Delhi
9,Charu Saini,Company Recruiter,OESPL PVT LTD,"Marketing, Civil Construction, Project Managem...",Noida
10,Cameo,Company Recruiter,Cameo Corporate Services,"Latex, Paginator, Tex",Chennai
11,Mr.Durjay,Company Recruiter,Hotel Chitvan,"Marketing, Digital Marketing, Google Adwords, ...",Ajmer
12,Prarit Gupta,Human Resource Manager,HMS Relations Management,"Counter Sales, Sales",Delhi
13,Raghu Hrexecutive,Human Resource manager,IQs soft,"Java/J2ee ( Core Java, Struts, Hibernate, Serv...",Bengaluru / Bangalore
14,Take jobs,Human Resources,Take Jobs,"tally, Bank Reconciliation, billing, electrica...",Delhi
15,iNFIN Technologies,Human Resources,Infin Software Technologies Pvt. Ltd,"Technical, PHP, Web Development, Web Technolog...",Chandigarh
16,Punit Kumar Bhidodiya,Human Resource Manager,Exatip Technologies,"Software Development, Business Development",Indore
17,Ishan Ahmed,Human Resource Manager,Jute Wonders Unlimited,Back Office,Delhi
18,Sreekanth Menon,Human Resources,Sterlite Technologies Ltd. Elitecore,"C++, Java/j2ee, C, Networking, Radius, Diamete...",Ahmedabad
19,Abhishek,Human Resource Manager,Infosys Technology,"Sap Abap, Sap Basis, Sap Fico, Sap Bi, java, C...",Hyderabad / Secunderabad
20,TechCube IT Services Pvt Ltd,Human Resource Manager,TechCube IT Services Pvt Ltd,Skills- Technical Troubleshooting / Sales / Up...,Mohali
21,Fatte Chand Soni,Human Resource Generalist,Tetraskelion Softwares (P) Ltd,".Net, Java, PHP, Android, Testing, IOS, Web an...",Jaipur
22,Koustav Bose,human resource manager,KKR BOSE DESIGN SERVICES PVT LTD,Ravit,Mumbai
23,Vaishambi Saxena,Human Resources,22Feet Tribal Worldwide (DDB Worldwide),"Magento, PHP, Content, Design, DotNet, BD",Bengaluru / Bangalore

In [169]:
#make csv file
df.to_csv('Data science recruiters')

In [170]:
#close the driver
driver.close()

##### 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/ 

You have to find the following details:
- Book name
- Author name 
- Volumes sold
- Publisher
- Genre

In [171]:
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'

In [172]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [173]:
#scrape book name
name=[]
try:
    names=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
print(len(name),name)

100 ['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [174]:
#scrape Author name
author=[]
try:
    authors=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for x in authors:
        author.append(x.text)
except NoSuchElementException:
    author.append('-')
except StaleElementReferenceException:
    author.append('-')
print(len(author),author)

100 ['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']

In [176]:
#scrape Volumes sold
sold=[]
try:
    solds=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for x in solds:
        sold.append(x.text)
except NoSuchElementException:
    sold.append('-')
except StaleElementReferenceException:
    sold.append('-')
print(len(sold),sold)

100 ['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']

In [178]:
#scrape publisher name
publisher=[]
try:
    publishers=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for x in publishers:
        publisher.append(x.text)
except NoSuchElementException:
    publisher.append('-')
except StaleElementReferenceException:
    publisher.append('-')
print(len(publisher),publisher)

100 ['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']

In [179]:
#scrape Genre name
genre=[]
try:
    genres=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for x in genres:
        genre.append(x.text)
except NoSuchElementException:
    genre.append('-')
except StaleElementReferenceException:
    genre.append('-')
print(len(genre),genre)

100 ['Crime, Thriller & Adventure', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Romance & Sagas', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Crime, Thriller & Adventure', "Children's Fiction", 'Romance & Sagas', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Romance & Sagas', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Popular Science', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Picture Books', 'Picture Books', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Humour: Collections & General', 'General & Literary Fiction', 'Autobiography: General', 'General & Literary Fiction', 'Biography: The Arts', 'Autobiography: General', 'Picture Books', 'Autobiography: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Science Fiction & Fantasy', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'Fitness & Diet', 'General & Literary Fiction', "Children's Fiction", 'Crime, Thriller & Adventure', 'Fitness & Diet', 'Young Adult Fiction', 'Usage & Writing Guides', 'Food & Drink: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Popular Culture & Media: General Interest', 'Autobiography: The Arts', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Science Fiction & Fantasy', 'Current Affairs & Issues', 'Crime, Thriller & Adventure', 'Autobiography: The Arts', 'General & Literary Fiction', 'Autobiography: The Arts', 'Travel Writing', 'Food & Drink: General', 'General & Literary Fiction', 'National & Regional Cuisine', 'Fitness & Diet', 'Travel Writing', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'Picture Books', 'General & Literary Fiction', 'Autobiography: The Arts', 'Popular Science', "Children's Annuals", 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Food & Drink: General', 'Young Adult Fiction', 'Biography: General', 'Food & Drink: General']

In [180]:
#make dataframe
df=pd.DataFrame()
df['Book name']=name
df['Author name']=author
df['Volumes sold']=sold
df['Publisher']=publisher
df['Genre']=genre
df

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [181]:
#make csv file
df.to_csv('Highest selling novels.csv')

In [182]:
#close the driver
driver.close()

##### 9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ 

You have to find the following details:
- Name 
- Year span 
- Genre 
- Run time 
- Ratings 
- Votes

In [183]:
url='https://www.imdb.com/list/ls095964455/'

In [184]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [185]:
#scrape movie name
name=[]
try:
    names=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a[1]')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
print(len(name),name)

100 ['Game of Thrones', 'Stranger Things', 'The Walking Dead', '13 Reasons Why', 'The 100', 'Orange Is the New Black', 'Riverdale', "Grey's Anatomy", 'The Flash', 'Arrow', 'Money Heist', 'The Big Bang Theory', 'Black Mirror', 'Sherlock', 'Vikings', 'Pretty Little Liars', 'The Vampire Diaries', 'American Horror Story', 'Breaking Bad', 'Lucifer', 'Supernatural', 'Prison Break', 'How to Get Away with Murder', 'Teen Wolf', 'The Simpsons', 'Once Upon a Time', 'Narcos', 'Daredevil', 'Friends', 'How I Met Your Mother', 'Suits', 'Mr. Robot', 'The Originals', 'Supergirl', 'Gossip Girl', 'Sense8', 'Gotham', 'Westworld', 'Jessica Jones', 'Modern Family', 'Rick and Morty', 'Shadowhunters', 'The End of the F***ing World', 'House of Cards', 'Dark', 'Elite', 'Sex Education', 'Shameless', 'New Girl', 'Agents of S.H.I.E.L.D.', 'You', 'Dexter', 'Fear the Walking Dead', 'Family Guy', 'The Blacklist', 'Lost', 'Peaky Blinders', 'House', 'Quantico', 'Orphan Black', 'Homeland', 'Blindspot', "DC's Legends of Tomorrow", "The Handmaid's Tale", 'Chilling Adventures of Sabrina', 'The Good Doctor', 'Jane the Virgin', 'Glee', 'South Park', 'Brooklyn Nine-Nine', 'Under the Dome', 'The Umbrella Academy', 'True Detective', 'The OA', 'Desperate Housewives', 'Better Call Saul', 'Bates Motel', 'The Punisher', 'Atypical', 'Dynasty', 'This Is Us', 'The Good Place', 'Iron Fist', 'The Rain', 'Mindhunter', 'Revenge', 'Luke Cage', 'Scandal', 'The Defenders', 'Big Little Lies', 'Insatiable', 'The Mentalist', 'The Crown', 'Chernobyl', 'iZombie', 'Reign', 'A Series of Unfortunate Events', 'Criminal Minds', 'Scream: The TV Series', 'The Haunting of Hill House']

In [186]:
#scrape Year span
year=[]
try:
    years=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]')
    for x in years:
        year.append(x.text)
except NoSuchElementException:
    year.append('-')
except StaleElementReferenceException:
    year.append('-')
print(len(year),year)

100 ['(2011–2019)', '(2016– )', '(2010–2022)', '(2017–2020)', '(2014–2020)', '(2013–2019)', '(2017–2023)', '(2005– )', '(2014– )', '(2012–2020)', '(2017–2021)', '(2007–2019)', '(2011–2019)', '(2010–2017)', '(2013–2020)', '(2010–2017)', '(2009–2017)', '(2011– )', '(2008–2013)', '(2016–2021)', '(2005–2020)', '(2005–2017)', '(2014–2020)', '(2011–2017)', '(1989– )', '(2011–2018)', '(2015–2017)', '(2015–2018)', '(1994–2004)', '(2005–2014)', '(2011–2019)', '(2015–2019)', '(2013–2018)', '(2015–2021)', '(2007–2012)', '(2015–2018)', '(2014–2019)', '(2016– )', '(2015–2019)', '(2009–2020)', '(2013– )', '(2016–2019)', '(2017–2019)', '(2013–2018)', '(2017–2020)', '(2018– )', '(2019– )', '(2011–2021)', '(2011–2018)', '(2013–2020)', '(2018– )', '(2006–2013)', '(2015– )', '(1999– )', '(2013– )', '(2004–2010)', '(2013–2022)', '(2004–2012)', '(2015–2018)', '(2013–2017)', '(2011–2020)', '(2015–2020)', '(2016–2022)', '(2017– )', '(2018–2020)', '(2017– )', '(2014–2019)', '(2009–2015)', '(1997– )', '(2013–2021)', '(2013–2015)', '(2019– )', '(2014–2019)', '(2016–2019)', '(2004–2012)', '(2015–2022)', '(2013–2017)', '(2017–2019)', '(2017–2021)', '(2017–2022)', '(2016–2022)', '(2016–2020)', '(2017–2018)', '(2018–2020)', '(2017–2019)', '(2011–2015)', '(2016–2018)', '(2012–2018)', '(2017)', '(2017–2019)', '(2018–2019)', '(2008–2015)', '(2016– )', '(2019)', '(2015–2019)', '(2013–2017)', '(2017–2019)', '(2005–2020)', '(2015–2019)', '(2018)']

In [187]:
#scrape Genre
genre=[]
try:
    genres=driver.find_elements_by_xpath('//span[@class="genre"]')
    for x in genres:
        genre.append(x.text)
except NoSuchElementException:
    genre.append('-')
except StaleElementReferenceException:
    genre.append('-')
print(len(genre),genre)

100 ['Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Horror, Thriller', 'Drama, Mystery, Thriller', 'Drama, Mystery, Sci-Fi', 'Comedy, Crime, Drama', 'Crime, Drama, Mystery', 'Drama, Romance', 'Action, Adventure, Drama', 'Action, Adventure, Crime', 'Action, Crime, Drama', 'Comedy, Romance', 'Drama, Mystery, Sci-Fi', 'Crime, Drama, Mystery', 'Action, Adventure, Drama', 'Drama, Mystery, Romance', 'Drama, Fantasy, Horror', 'Drama, Horror, Sci-Fi', 'Crime, Drama, Thriller', 'Crime, Drama, Fantasy', 'Drama, Fantasy, Horror', 'Action, Crime, Drama', 'Crime, Drama, Mystery', 'Action, Drama, Fantasy', 'Animation, Comedy', 'Adventure, Fantasy, Romance', 'Biography, Crime, Drama', 'Action, Crime, Drama', 'Comedy, Romance', 'Comedy, Romance', 'Comedy, Drama', 'Crime, Drama, Thriller', 'Drama, Fantasy, Horror', 'Action, Adventure, Drama', 'Drama, Romance', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Comedy, Drama, Romance', 'Animation, Adventure, Comedy', 'Action, Drama, Fantasy', 'Adventure, Comedy, Crime', 'Drama', 'Crime, Drama, Mystery', 'Crime, Drama, Thriller', 'Comedy, Drama', 'Comedy, Drama', 'Comedy, Romance', 'Action, Adventure, Drama', 'Crime, Drama, Romance', 'Crime, Drama, Mystery', 'Drama, Horror, Sci-Fi', 'Animation, Comedy', 'Crime, Drama, Mystery', 'Adventure, Drama, Fantasy', 'Crime, Drama', 'Drama, Mystery', 'Crime, Drama, Mystery', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Action, Crime, Drama', 'Action, Adventure, Drama', 'Drama, Sci-Fi, Thriller', 'Drama, Fantasy, Horror', 'Drama', 'Comedy', 'Comedy, Drama, Music', 'Animation, Comedy', 'Comedy, Crime', 'Drama, Mystery, Sci-Fi', 'Action, Adventure, Comedy', 'Crime, Drama, Mystery', 'Drama, Fantasy, Mystery', 'Comedy, Drama, Mystery', 'Crime, Drama', 'Drama, Horror, Mystery', 'Action, Crime, Drama', 'Comedy, Drama', 'Drama', 'Comedy, Drama, Romance', 'Comedy, Drama, Fantasy', 'Action, Adventure, Crime', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Drama, Mystery, Thriller', 'Action, Crime, Drama', 'Drama, Thriller', 'Action, Adventure, Crime', 'Crime, Drama, Mystery', 'Comedy, Drama, Thriller', 'Crime, Drama, Mystery', 'Biography, Drama, History', 'Drama, History, Thriller', 'Comedy, Crime, Drama', 'Drama, Fantasy', 'Adventure, Comedy, Drama', 'Crime, Drama, Mystery', 'Comedy, Crime, Drama', 'Drama, Horror, Mystery']

In [188]:
#scrape Run Time
time=[]
try:
    run=driver.find_elements_by_xpath('//span[@class="runtime"]')
    for x in run:
        time.append(x.text)
except NoSuchElementException:
    time.append('-')
except StaleElementReferenceException:
    time.append('-')
print(len(time),time)

100 ['57 min', '51 min', '44 min', '60 min', '43 min', '59 min', '45 min', '41 min', '43 min', '42 min', '70 min', '22 min', '60 min', '88 min', '44 min', '44 min', '43 min', '60 min', '49 min', '42 min', '44 min', '44 min', '43 min', '41 min', '22 min', '60 min', '49 min', '54 min', '22 min', '22 min', '44 min', '49 min', '45 min', '43 min', '42 min', '60 min', '42 min', '62 min', '56 min', '22 min', '23 min', '42 min', '25 min', '51 min', '60 min', '60 min', '45 min', '46 min', '22 min', '45 min', '45 min', '53 min', '44 min', '22 min', '43 min', '44 min', '60 min', '44 min', '42 min', '44 min', '55 min', '42 min', '42 min', '60 min', '60 min', '41 min', '60 min', '44 min', '22 min', '22 min', '43 min', '60 min', '55 min', '60 min', '45 min', '46 min', '45 min', '53 min', '30 min', '42 min', '45 min', '22 min', '55 min', '45 min', '60 min', '44 min', '55 min', '43 min', '50 min', '60 min', '45 min', '43 min', '58 min', '330 min', '42 min', '42 min', '50 min', '42 min', '45 min', '572 min']

In [189]:
#scrape Ratings
rating=[]
try:
    ratings=driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]/span[2]')
    for x in ratings:
        rating.append(x.text)
except NoSuchElementException:
    rating.append('-')
except StaleElementReferenceException:
    rating.append('-')
print(len(rating),rating)

100 ['9.2', '8.7', '8.2', '7.5', '7.6', '8.1', '6.7', '7.6', '7.6', '7.5', '8.2', '8.2', '8.8', '9.1', '8.5', '7.4', '7.7', '8', '9.5', '8.1', '8.5', '8.3', '8.1', '7.7', '8.7', '7.7', '8.8', '8.6', '8.9', '8.3', '8.5', '8.6', '8.3', '6.2', '7.4', '8.2', '7.8', '8.6', '7.9', '8.5', '9.2', '6.4', '8.1', '8.7', '8.7', '7.4', '8.4', '8.6', '7.7', '7.5', '7.7', '8.7', '6.8', '8.2', '8', '8.4', '8.8', '8.7', '6.6', '8.3', '8.3', '7.3', '6.7', '8.4', '7.4', '8.1', '7.9', '6.8', '8.7', '8.4', '6.5', '8', '8.9', '7.8', '7.6', '8.8', '8.2', '8.5', '8.3', '7.2', '8.7', '8.2', '6.5', '6.3', '8.6', '7.8', '7.3', '7.7', '7.3', '8.5', '6.5', '8.1', '8.7', '9.4', '7.8', '7.4', '7.8', '8.1', '7.1', '8.6']

In [191]:
#scrape votes
vote=[]
try:
    votes=driver.find_elements_by_xpath('//div[@class="lister-item-content"]/p[4]/span[2]')
    for x in votes:
        vote.append(x.text)
except NoSuchElementException:
    vote.append('-')
except StaleElementReferenceException:
    vote.append('-')
print(len(vote),vote)

100 ['1,990,259', '1,007,688', '947,735', '283,147', '242,955', '296,176', '139,679', '294,904', '337,866', '426,175', '456,768', '784,060', '518,284', '894,386', '510,402', '163,471', '311,570', '307,637', '1,739,646', '309,143', '429,753', '518,386', '147,178', '143,174', '395,816', '220,759', '405,920', '421,258', '953,506', '663,743', '396,821', '374,905', '131,976', '122,139', '170,094', '151,853', '226,555', '476,779', '209,602', '411,038', '476,802', '61,290', '178,822', '495,021', '356,334', '73,692', '261,496', '230,931', '216,899', '214,034', '226,825', '712,579', '127,131', '328,127', '239,571', '537,667', '489,743', '449,512', '60,394', '109,016', '335,655', '72,545', '102,945', '217,307', '90,704', '89,279', '48,058', '145,771', '360,439', '295,236', '105,532', '204,450', '548,250', '102,302', '126,246', '414,780', '105,621', '221,511', '83,795', '21,262', '135,865', '149,718', '127,497', '35,972', '270,266', '118,922', '127,906', '72,620', '103,936', '189,817', '27,456', '180,285', '191,637', '700,321', '66,664', '48,775', '59,428', '189,884', '40,206', '227,963']

In [192]:
#make dataframe
df=pd.DataFrame()
df['Movie Name']=name
df['Year span']=year
df['Genre']=genre
df['Run Time']=time
df['Ratings']=rating
df['Votes']=vote
df

,Movie Name,Year span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,990,259"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,007,688"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"947,735"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"283,147"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"242,955"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,775"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,428"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"189,884"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,206"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"227,963"

In [193]:
#make csv file
df.to_csv('most watched tv series.csv')

In [194]:
#close the driver
driver.close()

##### 10. Details of Datasets from UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/ 

You have to find the following details:
- Dataset name 
- Data type 
- Task 
- Attribute type 
- No of instances 
- No of attribute 
- Year

In [195]:
url='https://archive.ics.uci.edu/'

In [196]:
#open web driver
driver=webdriver.Chrome(r"C:\Users\dell\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)

In [197]:
#open view all datasets
data_sets=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a')
try:
    data_sets.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(data_sets.get_attribute('href'))

In [201]:
#scrape Dataset name
name=[]
try:
    names=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td/table/tbody/tr/td[2]/p/b/a')
    for x in names:
        name.append(x.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
print(len(name),name)

622 ['Abalone', 'Adult', 'Annealing', 'Anonymous Microsoft Web Data', 'Arrhythmia', 'Artificial Characters', 'Audiology (Original)', 'Audiology (Standardized)', 'Auto MPG', 'Automobile', 'Badges', 'Balance Scale', 'Balloons', 'Breast Cancer', 'Breast Cancer Wisconsin (Original)', 'Breast Cancer Wisconsin (Prognostic)', 'Breast Cancer Wisconsin (Diagnostic)', 'Pittsburgh Bridges', 'Car Evaluation', 'Census Income', 'Chess (King-Rook vs. King-Knight)', 'Chess (King-Rook vs. King-Pawn)', 'Chess (King-Rook vs. King)', 'Chess (Domain Theories)', 'Bach Chorales', 'Connect-4', 'Credit Approval', 'Japanese Credit Screening', 'Computer Hardware', 'Contraceptive Method Choice', 'Covertype', 'Cylinder Bands', 'Dermatology', 'Diabetes', 'DGP2 - The Second Data Generation Program', 'Document Understanding', 'EBL Domain Theories', 'Echocardiogram', 'Ecoli', 'Flags', 'Function Finding', 'Glass Identification', "Haberman's Survival", 'Hayes-Roth', 'Heart Disease', 'Hepatitis', 'Horse Colic', 'ICU', 'Image Segmentation', 'Internet Advertisements', 'Ionosphere', 'Iris', 'ISOLET', 'Kinship', 'Labor Relations', 'LED Display Domain', 'Lenses', 'Letter Recognition', 'Liver Disorders', 'Logic Theorist', 'Lung Cancer', 'Lymphography', 'Mechanical Analysis', 'Meta-data', 'Mobile Robots', 'Molecular Biology (Promoter Gene Sequences)', 'Molecular Biology (Protein Secondary Structure)', 'Molecular Biology (Splice-junction Gene Sequences)', "MONK's Problems", 'Moral Reasoner', 'Multiple Features', 'Mushroom', 'Musk (Version 1)', 'Musk (Version 2)', 'Nursery', 'Othello Domain Theory', 'Page Blocks Classification', 'Optical Recognition of Handwritten Digits', 'Pen-Based Recognition of Handwritten Digits', 'Post-Operative Patient', 'Primary Tumor', 'Prodigy', 'Qualitative Structure Activity Relationships', 'Quadruped Mammals', 'Servo', 'Shuttle Landing Control', 'Solar Flare', 'Soybean (Large)', 'Soybean (Small)', 'Challenger USA Space Shuttle O-Ring', 'Low Resolution Spectrometer', 'Spambase', 'SPECT Heart', 'SPECTF Heart', 'Sponge', 'Statlog Project', 'Student Loan Relational', 'Teaching Assistant Evaluation', 'Tic-Tac-Toe Endgame', 'Thyroid Disease', 'Trains', 'University', 'Congressional Voting Records', 'Water Treatment Plant', 'Waveform Database Generator (Version 1)', 'Waveform Database Generator (Version 2)', 'Wine', 'Yeast', 'Zoo', 'Undocumented', 'Twenty Newsgroups', 'Australian Sign Language signs', 'Australian Sign Language signs (High Quality)', 'US Census Data (1990)', 'Census-Income (KDD)', 'Coil 1999 Competition Data', 'Corel Image Features', 'E. Coli Genes', 'EEG Database', 'El Nino', 'Entree Chicago Recommendation Data', 'CMU Face Images', 'Insurance Company Benchmark (COIL 2000)', 'Internet Usage Data', 'IPUMS Census Database', 'Japanese Vowels', 'KDD Cup 1998 Data', 'KDD Cup 1999 Data', 'M. Tuberculosis Genes', 'Movie', 'MSNBC.com Anonymous Web Data', 'NSF Research Award Abstracts 1990-2003', 'Pioneer-1 Mobile Robot Data', 'Pseudo Periodic Synthetic Time Series', 'Reuters-21578 Text Categorization Collection', 'Robot Execution Failures', 'Synthetic Control Chart Time Series', 'Syskill and Webert Web Page Ratings', 'UNIX User Data', 'Volcanoes on Venus - JARtool experiment', 'Statlog (Australian Credit Approval)', 'Statlog (German Credit Data)', 'Statlog (Heart)', 'Statlog (Landsat Satellite)', 'Statlog (Image Segmentation)', 'Statlog (Shuttle)', 'Statlog (Vehicle Silhouettes)', 'Connectionist Bench (Nettalk Corpus)', 'Connectionist Bench (Sonar, Mines vs. Rocks)', 'Connectionist Bench (Vowel Recognition - Deterding Data)', 'Economic Sanctions', 'Protein Data', 'Cloud', 'CalIt2 Building People Counts', 'Dodgers Loop Sensor', 'Poker Hand', 'MAGIC Gamma Telescope', 'UJI Pen Characters', 'Mammographic Mass', 'Forest Fires', 'Reuters Transcribed Subset', 'Bag of Words', 'Concrete Compressive Strength', 'Hill-Valley', 'Arcene', 'Dexter', 'Dorothea', 'Gisette', 'Madelon', 'Ozone Level Detection', 'Abscisic Acid Signaling Network', 'Parkinsons', 'Character Trajectories', 'Blood Transfusion Service Center', 'UJI Pen Characters (Version 2)', 'Semeion Handwritten Digit', 'SECOM', 'Plants', 'Libras Movement', 'Concrete Slump Test', 'Communities and Crime', 'Acute Inflammations', 'Wine Quality', 'URL Reputation', 'p53 Mutants', 'Parkinsons Telemonitoring', 'Demospongiae', 'Opinosis Opinion ⁄ Review', 'Breast Tissue', 'Cardiotocography', 'Wall-Following Robot Navigation Data', 'Spoken Arabic Digit', 'Localization Data for Person Activity', 'AutoUniv', 'Steel Plates Faults', 'MiniBooNE particle identification', 'YearPredictionMSD', 'PEMS-SF', 'OpinRank Review Dataset', 'Relative location of CT slices on axial axis', 'Online Handwritten Assamese Characters Dataset', 'PubChem Bioassay Data', 'Record Linkage Comparison Patterns', 'Communities and Crime Unnormalized', 'Vertebral Column', 'EMG Physical Action Data Set', 'Vicon Physical Action Data Set', 'Amazon Commerce reviews set', 'Amazon Access Samples', 'Reuter_50_50', 'Farm Ads', 'DBWorld e-mails', 'KEGG Metabolic Relation Network (Directed)', 'KEGG Metabolic Reaction Network (Undirected)', 'Bank Marketing', 'YouTube Comedy Slam Preference Data', 'Gas Sensor Array Drift Dataset', 'ILPD (Indian Liver Patient Dataset)', 'OPPORTUNITY Activity Recognition', 'Nomao', 'SMS Spam Collection', 'Skin Segmentation', 'Planning Relax', 'PAMAP2 Physical Activity Monitoring', 'Restaurant & consumer data', 'CNAE-9', 'Individual household electric power consumption', 'seeds', 'Northix', 'QtyT40I10D100K', 'Legal Case Reports', 'Human Activity Recognition Using Smartphones', 'One-hundred plant species leaves data set', 'Energy efficiency', 'Yacht Hydrodynamics', 'Fertility', 'Daphnet Freezing of Gait', '3D Road Network (North Jutland, Denmark)', 'ISTANBUL STOCK EXCHANGE', 'Buzz in social media', 'First-order theorem proving', 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)', 'Gas sensor arrays in open sampling settings', 'Climate Model Simulation Crashes', 'MicroMass', 'QSAR biodegradation', 'BLOGGER', 'Daily and Sports Activities', 'User Knowledge Modeling', 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection', 'NYSK', 'Turkiye Student Evaluation', "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)", 'EEG Eye State', 'Physicochemical Properties of Protein Tertiary Structure', 'seismic-bumps', 'banknote authentication', 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat', 'YouTube Multiview Video Games Dataset', 'Gas Sensor Array Drift Dataset at Different Concentrations', 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors', 'SkillCraft1 Master Table Dataset', 'Weight Lifting Exercises monitored with Inertial Measurement Units', 'SML2010', 'Bike Sharing Dataset', 'Predict keywords activities in a online social media', 'Thoracic Surgery Data', 'EMG dataset in Lower Limb', 'SUSY', 'HIGGS', 'Qualitative_Bankruptcy', 'LSVT Voice Rehabilitation', 'Dataset for ADL Recognition with Wrist-worn Accelerometer', 'Wilt', 'User Identification From Walking Activity', 'Activity Recognition from Single Chest-Mounted Accelerometer', 'Leaf', 'Dresses_Attribute_Sales', 'Tamilnadu Electricity Board Hourly Readings', 'Airfoil Self-Noise', 'Wholesale customers', 'Twitter Data set for Arabic Sentiment Analysis', 'Combined Cycle Power Plant', 'Urban Land Cover', 'Diabetes 130-US hospitals for years 1999-2008', 'Bach Choral Harmony', 'StoneFlakes', 'Tennis Major Tournament Match Statistics', 'Parkinson Speech Dataset with Multiple Types of Sound Recordings', 'Gesture Phase Segmentation', 'Perfume Data', 'BlogFeedback', 'REALDISP Activity Recognition Dataset', 'Newspaper and magazine images segmentation dataset', 'AAAI 2014 Accepted Papers', 'Gas sensor array under flow modulation', 'Gas sensor array exposed to turbulent gas mixtures', 'UJIIndoorLoc', 'Sentence Classification', 'Dow Jones Index', 'sEMG for Basic Hand movements', 'AAAI 2013 Accepted Papers', 'Geographical Original of Music', 'Condition Based Maintenance of Naval Propulsion Plants', 'Grammatical Facial Expressions', 'NoisyOffice', 'MHEALTH Dataset', 'Student Performance', 'ElectricityLoadDiagrams20112014', 'Gas sensor array under dynamic gas mixtures', 'microblogPCU', 'Firm-Teacher_Clave-Direction_Classification', 'Dataset for Sensorless Drive Diagnosis', 'TV News Channel Commercial Detection Dataset', 'Phishing Websites', 'Greenhouse Gas Observing Network', 'Diabetic Retinopathy Debrecen Data Set', 'HIV-1 protease cleavage', 'Sentiment Labelled Sentences', 'Online News Popularity', 'Forest type mapping', 'wiki4HE', 'Online Video Characteristics and Transcoding Time Dataset', 'Chronic_Kidney_Disease', 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014', 'Folio', 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015', 'Cuff-Less Blood Pressure Estimation', 'Smartphone-Based Recognition of Human Activities and Postural Transitions', 'Mice Protein Expression', 'UJIIndoorLoc-Mag', 'Heterogeneity Activity Recognition', 'Educational Process Mining (EPM): A Learning Analytics Data Set', 'HEPMASS', 'Indoor User Movement Prediction from RSS data', 'Open University Learning Analytics dataset', 'default of credit card clients', 'Mesothelioma’s disease data set', 'Online Retail', 'SIFT10M', 'GPS Trajectories', 'Detect Malacious Executable(AntiVirus)', 'Occupancy Detection', 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease', 'News Aggregator', 'Air Quality', 'Twin gas sensor arrays', 'Gas sensors for home activity monitoring', 'Facebook Comment Volume Dataset', 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)', 'Polish companies bankruptcy data', 'Activity Recognition system based on Multisensor data fusion (AReM)', 'Dota2 Games Results', 'Facebook metrics', 'UbiqLog (smartphone lifelogging)', 'NIPS Conference Papers 1987-2015', 'HTRU2', 'Drug consumption (quantified)', 'Appliances energy prediction', 'Miskolc IIS Hybrid IPS', 'KDC-4007 dataset Collection', 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone', 'DrivFace', 'Website Phishing', 'YouTube Spam Collection', 'Beijing PM2.5 Data', 'Cargo 2000 Freight Tracking and Tracing', 'Cervical cancer (Risk Factors)', 'Quality Assessment of Digital Colposcopies', 'KASANDR', 'FMA: A Dataset For Music Analysis', 'Air quality', 'Epileptic Seizure Recognition', 'Devanagari Handwritten Character Dataset', 'Stock portfolio performance', 'MoCap Hand Postures', 'Early biomarkers of Parkinson�s disease based on natural connected speech', 'Data for Software Engineering Teamwork Assessment in Education Setting', 'PM2.5 Data of Five Chinese Cities', 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet', 'Sales_Transactions_Dataset_Weekly', 'Las Vegas Strip', 'Eco-hotel', 'MEU-Mobile KSD', 'Crowdsourced Mapping', 'gene expression cancer RNA-Seq', 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer', 'chestnut – LARVIC', 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network', 'Motion Capture Hand Postures', 'Anuran Calls (MFCCs)', 'TTC-3600: Benchmark dataset for Turkish text categorization', 'Gastrointestinal Lesions in Regular Colonoscopy', 'Daily Demand Forecasting Orders', 'Paper Reviews', 'extention of Z-Alizadeh sani dataset', 'Z-Alizadeh Sani', 'Dynamic Features of VirusShare Executables', 'IDA2016Challenge', 'DSRC Vehicle Communications', 'Mturk User-Perceived Clusters over Images', 'Character Font Images', 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels', 'Autistic Spectrum Disorder Screening Data for Children', 'Autistic Spectrum Disorder Screening Data for Adolescent', 'APS Failure at Scania Trucks', 'Wireless Indoor Localization', 'HCC Survival', 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015', 'University of Tehran Question Dataset 2016 (UTQD.2016)', 'Autism Screening Adult', 'Activity recognition with healthy older people using a batteryless wearable sensor', 'Immunotherapy Dataset', 'Cryotherapy Dataset', 'OCT data & Color Fundus Images of Left & Right Eyes', 'Discrete Tone Image Dataset', 'News Popularity in Multiple Social Media Platforms', 'Ultrasonic flowmeter diagnostics', 'ICMLA 2014 Accepted Papers Data Set', 'BLE RSSI Dataset for Indoor localization and Navigation', 'Container Crane Controller Data Set', 'Residential Building Data Set', 'Health News in Twitter', 'chipseq', 'SGEMM GPU kernel performance', 'Repeat Consumption Matrices', 'detection_of_IoT_botnet_attacks_N_BaIoT', 'Absenteeism at work', 'SCADI', 'Condition monitoring of hydraulic systems', 'Carbon Nanotubes', 'Optical Interconnection Network', 'Sports articles for objectivity analysis', 'Breast Cancer Coimbra', 'GNFUV Unmanned Surface Vehicles Sensor Data', 'Dishonest Internet users Dataset', 'Victorian Era Authorship Attribution', 'Simulated Falls and Daily Living Activities Data Set', 'Multimodal Damage Identification for Humanitarian Computing', 'EEG Steady-State Visual Evoked Potential Signals', 'Roman Urdu Data Set', 'Avila', 'PANDOR', 'Drug Review Dataset (Druglib.com)', 'Drug Review Dataset (Drugs.com)', 'Physical Unclonable Functions', 'Superconductivty Data', 'WESAD (Wearable Stress and Affect Detection)', 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2', 'Student Academics Performance', 'Online Shoppers Purchasing Intention Dataset', 'PMU-UD', "Parkinson's Disease Classification", 'Electrical Grid Stability Simulated Data', 'Caesarian Section Classification Dataset', 'BAUM-1', 'BAUM-2', 'Audit Data', 'BuddyMove Data Set', 'Real estate valuation data set', 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set', 'Somerville Happiness Survey', '2.4 GHZ Indoor Channel Measurements', 'EMG data for gestures', 'Parking Birmingham', 'Behavior of the urban traffic of the city of Sao Paulo in Brazil', 'Travel Reviews', 'Tarvel Review Ratings', 'Rice Leaf Diseases', 'Gas sensor array temperature modulation', 'Facebook Live Sellers in Thailand', 'Parkinson Dataset with replicated acoustic features', 'Metro Interstate Traffic Volume', 'Query Analytics Workloads Dataset', 'Wave Energy Converters', 'PPG-DaLiA', 'Alcohol QCM Sensor Dataset', 'Divorce Predictors data set', 'Incident management process enriched event log', 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)', 'MEx', 'Beijing Multi-Site Air-Quality Data', 'Online Retail II', 'Hepatitis C Virus (HCV) for Egyptian patients', 'QSAR fish toxicity', 'QSAR aquatic toxicity', 'Human Activity Recognition from Continuous Ambient Sensor Data', 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset', 'QSAR oral toxicity', 'QSAR androgen receptor', 'QSAR Bioconcentration classes dataset', 'QSAR fish bioconcentration factor (BCF)', 'A study of Asian Religious and Biblical Texts', 'Real-time Election Results: Portugal 2019', 'Bias correction of numerical prediction model temperature forecast', 'Bar Crawl: Detecting Heavy Drinking', 'Kitsune Network Attack Dataset', 'Shoulder Implant X-Ray Manufacturer Classification', 'Speaker Accent Recognition', 'Heart failure clinical records', 'Deepfakes: Medical Image Tamper Detection', 'selfBACK', 'South German Credit', 'Exasens', 'Swarm Behaviour', 'Crop mapping using fused optical-radar data set', 'BitcoinHeistRansomwareAddressDataset', 'Facebook Large Page-Page Network', 'Amphibians', 'Early stage diabetes risk prediction dataset.', 'Turkish Spam V01', 'Stock keeping units', 'Demand Forecasting for a store', 'Detect Malware Types', 'Wave Energy Converters', 'Youtube cookery channels viewers comments in Hinglish', 'Pedestrian in Traffic Dataset', 'Cervical Cancer Behavior Risk', 'Sattriya_Dance_Single_Hand_Gestures Dataset', 'Divorce Predictors data set', '3W dataset', 'Malware static and dynamic features VxHeaven and Virus Total', 'Internet Firewall Data', 'User Profiling and Abusive Language Detection Dataset', 'Estimation of obesity levels based on eating habits and physical condition', 'Rice (Cammeo and Osmancik)', 'Vehicle routing and scheduling problems', 'Algerian Forest Fires Dataset', 'Breath Metabolomics', 'Horton General Hospital', 'UrbanGB, urban road accidents coordinates labelled by the urban center', 'Gas Turbine CO and NOx Emission Data Set', 'Activity recognition using wearable physiological measurements', 'clickstream data for online shopping', 'CNNpred: CNN-based stock market prediction using a diverse set of variables', 'Apartment for rent classified', ': Simulated Data set of Iraqi tourism places', 'Nasarian CAD Dataset', 'Monolithic Columns in Troad and Mysia Region', 'Bar Crawl: Detecting Heavy Drinking', 'Seoul Bike Sharing Demand', 'Person Classification Gait Data', 'Shill Bidding Dataset', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Bone marrow transplant: children', 'Exasens', 'COVID-19 Surveillance', 'Refractive errors', 'Shoulder Implant X-Ray Manufacturer Classification', 'CLINC150', 'HCV data', 'Taiwanese Bankruptcy Prediction', 'South German Credit (UPDATE)', 'IIWA14-R820-Gazebo-Dataset-10Trajectories', 'Guitar Chords finger positions', 'Russian Corpus of Biographical Texts', 'Codon usage', 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset', 'Myocardial infarction complications', 'Hungarian Chickenpox Cases', 'Simulated data for survival modelling', 'Student Performance on an entrance examination', 'Chemical Composition of Ceramic Samples', 'Labeled Text Forum Threads Dataset', 'Stock keeping units', 'BLE RSSI dataset for Indoor localization', 'Basketball dataset', 'GitHub MUSAE', 'Anticancer peptides', 'Monolithic Columns in Troad and Mysia Region', 'Gender by Name', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Shoulder Implant Manufacture Classification', 'LastFM Asia Social Network', 'Wheat kernels', 'Productivity Prediction of Garment Employees', 'Multi-view Brain Networks', 'LastFM Asia Social Network', 'Wisesight Sentiment Corpus', 'AI4I 2020 Predictive Maintenance Dataset', 'Dry Bean Dataset', 'in-vehicle coupon recommendation', 'Gait Classification', 'Wikipedia Math Essentials', 'Wikipedia Math Essentials', 'Synchronous Machine Data Set', 'Average Localization Error (ALE) in sensor node localization process in WSNs', '9mers from cullpdb', 'TamilSentiMix', 'Accelerometer', 'Synchronous Machine Data Set', 'Pedal Me Bicycle Deliveries', 'Turkish Headlines Dataset', 'Secondary Mushroom Dataset', 'Power consumption of Tetouan city', 'Raisin Dataset', 'Steel Industry Energy Consumption Dataset', 'Gender Gap in Spanish WP', 'Non verbal tourists data', 'Roman Urdu Sentiment Analysis Dataset (RUSAD)', 'TUANDROMD ( Tezpur University Android Malware Dataset)', 'Higher Education Students Performance Evaluation Dataset', 'Risk Factor prediction of Chronic Kidney Disease', 'Lab Test', 'Shoulder Implant Manufacture Classification', 'Rocket League Skillshots Data Set', 'Sepsis survival minimal clinical records', 'Water Quality Prediction', 'Traffic Flow Forecasting', 'sentiment analysis in Saudi Arabia about distance education during Covid-19', 'Kain Tradisional Sambas', 'Image Recognition Task Execution Times in Mobile Edge Computing', 'REWEMA', 'REJAFADA', 'Steel Industry Energy Consumption Dataset', 'Influenza outbreak event prediction via Twitter data', 'Turkish Music Emotion Dataset', 'Maternal Health Risk Data Set', 'Room Occupancy Estimation', 'Image Recognition Task Execution Times in Mobile Edge Computing']

In [205]:
#scrape Data type
data=[]
try:
    datas=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p')
    for x in datas:
        data.append(x.text)
except NoSuchElementException:
    data.append('-')
except StaleElementReferenceException:
    data.append('-')
data=data[1:]#first row is title of table 'Data Types'
print(len(data),data)

622 ['Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Univariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Univariate, Time-Series ', 'Multivariate, Spatial ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Data-Generator ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Sequential, Domain-Theory ', 'Sequential ', 'Sequential, Domain-Theory ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Domain-Theory ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Time-Series ', 'Spatio-temporal ', 'Transactional, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Relational ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', 'Univariate, Time-Series ', 'Text ', 'Multivariate, Time-Series ', 'Time-Series ', 'Multivariate, Text ', 'Text, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Text ', 'Text ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Domain-Theory ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate, Text, Domain-Theory ', 'Time-Series, Domain-Theory ', 'Multivariate, Text, Domain-Theory ', 'Text ', 'Text ', 'Multivariate, Univariate, Text ', 'Multivariate, Univariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate, Text, Domain-Theory ', 'Univariate ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate, Text ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Sequential, Text ', 'Multivariate, Univariate, Time-Series ', 'Time-Series, Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Text ', 'Univariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Univariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series, Domain-Theory ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Time-Series ', 'Text ', ' ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Sequential, Text ', 'Multivariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', ' ', 'Sequential ', 'Univariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Text ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Time-Series ', 'Multivariate, Univariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Sequential ', 'Text ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Univariate ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Text ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Sequential, Time-Series ', 'Time-Series ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Sequential ', ' ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Text ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Univariate ']

In [208]:
#scrape Task
task=[]
try:
    tasks=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p')
    for x in tasks:
        task.append(x.text)
except NoSuchElementException:
    task.append('-')
except StaleElementReferenceException:
    task.append('-')
task=task[1:]#first row is title of table 'Defult Task'
print(len(task),task)

622 ['Classification ', 'Classification ', 'Classification ', 'Recommender-Systems ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Function-Learning ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Relational-Learning ', ' ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Recommender-Systems ', 'Classification ', 'Regression, Description ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', ' ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Regression, Clustering ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering ', 'Classification, Regression ', 'Regression, Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering, Causa ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Regression ', ' ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression, Clustering ', 'Classification, Regression ', 'Classification, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification, Regression, Clustering ', 'Clustering ', 'Classification, Regression ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Clustering ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Recommendation ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Regression, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Causal-Discovery ', 'Clustering ', 'Regression, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ']

In [211]:
#scrape Attribute type
attribute_type=[]
try:
    types=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p')
    for x in types:
        attribute_type.append(x.text)
except NoSuchElementException:
    attribute_type.append('-')
except StaleElementReferenceException:
    attribute_type.append('-')
attribute_type=attribute_type[1:]#first row is title of table 'Attribute Types'
print(len(attribute_type),attribute_type)

622 ['Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical, Real ', 'Categorical, Integer, Real ', ' ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Real ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Real, Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', ' ', ' ', 'Categorical, Integer, Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Real ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Integer ', 'Categorical, Integer, Real ', ' ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', ' ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Integer ', 'Categorical ', ' ', 'Integer, Real ', 'Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Real ', 'Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Real ', 'Real ', ' ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical ', ' ', 'Categorical, Real ', ' ', 'Categorical ', 'Integer ', 'Real ', 'Categorical ', ' ', ' ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Categorical ', 'Real ', 'Real ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Integer ', 'Integer ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Categorical ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', ' ', 'Integer ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Categorical ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', 'Integer, Real ', ' ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Integer ', 'Integer ', 'Integer ', ' ', 'Real ', 'Categorical ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', ' ', 'Integer, Real ', 'Real ', 'Integer ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Integer ', ' ', 'Real ', ' ', 'Real ', 'Integer ', ' ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', ' ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', ' ', ' ', 'Real ', ' ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', 'Real ', 'Real ']

In [212]:
#scrape No of instances
instance=[]
try:
    instances=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')
    for x in instances:
        instance.append(x.text)
except NoSuchElementException:
    instance.append('-')
except StaleElementReferenceException:
    instance.append('-')
instance=instance[1:]#first row is title of table 'No of Instances'
print(len(instance),instance)

622 ['4177 ', '48842 ', '798 ', '37711 ', '452 ', '6000 ', '226 ', '226 ', '398 ', '205 ', '294 ', '625 ', '16 ', '286 ', '699 ', '198 ', '569 ', '108 ', '1728 ', '48842 ', ' ', '3196 ', '28056 ', ' ', '100 ', '67557 ', '690 ', '125 ', '209 ', '1473 ', '581012 ', '512 ', '366 ', ' ', ' ', ' ', ' ', '132 ', '336 ', '194 ', '352 ', '214 ', '306 ', '160 ', '303 ', '155 ', '368 ', ' ', '2310 ', '3279 ', '351 ', '150 ', '7797 ', '104 ', '57 ', ' ', '24 ', '20000 ', '345 ', ' ', '32 ', '148 ', '209 ', '528 ', ' ', '106 ', '128 ', '3190 ', '432 ', '202 ', '2000 ', '8124 ', '476 ', '6598 ', '12960 ', ' ', '5473 ', '5620 ', '10992 ', '90 ', '339 ', ' ', ' ', ' ', '167 ', '15 ', '1389 ', '307 ', '47 ', '23 ', '531 ', '4601 ', '267 ', '267 ', '76 ', ' ', '1000 ', '151 ', '958 ', '7200 ', '10 ', '285 ', '435 ', '527 ', '5000 ', '5000 ', '178 ', '1484 ', '101 ', ' ', '20000 ', '6650 ', '2565 ', '2458285 ', '299285 ', '340 ', '68040 ', ' ', '122 ', '178080 ', '50672 ', '640 ', '9000 ', '10104 ', '256932 ', '640 ', '191779 ', '4000000 ', ' ', '10000 ', '989818 ', '129000 ', ' ', '100000 ', '21578 ', '463 ', '600 ', '332 ', ' ', ' ', '690 ', '1000 ', '270 ', '6435 ', '2310 ', '58000 ', '946 ', '20008 ', '208 ', '528 ', ' ', ' ', '1024 ', '10080 ', '50400 ', '1025010 ', '19020 ', '1364 ', '961 ', '517 ', '200 ', '8000000 ', '1030 ', '606 ', '900 ', '2600 ', '1950 ', '13500 ', '4400 ', '2536 ', '300 ', '197 ', '2858 ', '748 ', '11640 ', '1593 ', '1567 ', '22632 ', '360 ', '103 ', '1994 ', '120 ', '4898 ', '2396130 ', '16772 ', '5875 ', '503 ', '51 ', '106 ', '2126 ', '5456 ', '8800 ', '164860 ', ' ', '1941 ', '130065 ', '515345 ', '440 ', ' ', '53500 ', '8235 ', ' ', '5749132 ', '2215 ', '310 ', '10000 ', '3000 ', '1500 ', '30000 ', '2500 ', '4143 ', '64 ', '53414 ', '65554 ', '45211 ', '1138562 ', '13910 ', '583 ', '2551 ', '34465 ', '5574 ', '245057 ', '182 ', '3850505 ', '138 ', '1080 ', '2075259 ', '210 ', '115 ', '3960456 ', ' ', '10299 ', '1600 ', '768 ', '308 ', '100 ', '237 ', '434874 ', '536 ', '140000 ', '6118 ', '165632 ', '18000 ', '540 ', '931 ', '1055 ', '100 ', '9120 ', '403 ', '111740 ', '10421 ', '5820 ', '403 ', '14980 ', '45730 ', '2584 ', '1372 ', '306 ', '120000 ', '13910 ', '2747 ', '3395 ', '39242 ', '4137 ', '17389 ', '51 ', '470 ', '132 ', '5000000 ', '11000000 ', '250 ', '126 ', ' ', '4889 ', ' ', ' ', '340 ', '501 ', '45781 ', '1503 ', '440 ', '2000 ', '9568 ', '168 ', '100000 ', '5665 ', '79 ', '127 ', '1040 ', '9900 ', '560 ', '60021 ', '1419 ', '101 ', '399 ', '58 ', '180 ', '21048 ', ' ', '750 ', '3000 ', '150 ', '1059 ', '11934 ', '27965 ', '216 ', '120 ', '649 ', '370 ', '4178504 ', '221579 ', '10800 ', '58509 ', '129685 ', '2456 ', '2921 ', '1151 ', '6590 ', '3000 ', '39797 ', '326 ', '913 ', '168286 ', '400 ', '314080 ', '637 ', '1710671 ', '12000 ', '10929 ', '1080 ', '40000 ', '43930257 ', '230318 ', '10500000 ', '13197 ', ' ', '30000 ', '324 ', '541909 ', '11164866 ', '163 ', '373 ', '20560 ', '40 ', '422937 ', '9358 ', '640 ', '919438 ', '40949 ', '5744 ', '10503 ', '42240 ', '102944 ', '500 ', '9782222 ', '11463 ', '17898 ', '1885 ', '19735 ', '1540 ', '4007 ', '153540 ', '606 ', '1353 ', '1956 ', '43824 ', '3942 ', '858 ', '287 ', '17764280 ', '106574 ', '9358 ', '11500 ', '92000 ', '315 ', '78095 ', '130 ', '74 ', '52854 ', '77 ', '811 ', '504 ', '401 ', '2856 ', '10546 ', '801 ', '1540 ', '1451 ', '1075 ', '78095 ', '7195 ', '3600 ', '76 ', '60 ', '405 ', '303 ', '303 ', '107888 ', '76000 ', '10000 ', '180 ', '745000 ', '12234 ', '292 ', '104 ', '60000 ', '2000 ', '165 ', '217 ', '1175 ', '704 ', '75128 ', '90 ', '90 ', '50 ', '71 ', '93239 ', '540 ', '105 ', '6611 ', '15 ', '372 ', '58000 ', '4960 ', '241600 ', '130000 ', '7062606 ', '740 ', '70 ', '2205 ', '10721 ', '640 ', '1000 ', '116 ', '1672 ', '322 ', '93600 ', '3060 ', '5879 ', '9200 ', '20000 ', '20867 ', ' ', '4143 ', '215063 ', '6000000 ', '21263 ', '63000000 ', '10190 ', '300 ', '12330 ', '5180 ', '756 ', '10000 ', '80 ', '1184 ', '1047 ', '777 ', '249 ', '414 ', ' ', '143 ', '7840 ', '30000 ', '35717 ', '135 ', '980 ', '5456 ', '120 ', '4095000 ', '7051 ', '240 ', '48204 ', '260000 ', '288000 ', '8300000 ', '125 ', '170 ', '141712 ', '3916 ', '6262 ', '420768 ', '1067371 ', '1385 ', '908 ', '546 ', '13956534 ', '15630426 ', '8992 ', '1687 ', '779 ', '1056 ', '590 ', '21643 ', '7750 ', '14057567 ', '27170754 ', '597 ', '329 ', '299 ', '20000 ', '26136 ', '1000 ', '399 ', '24017 ', '325834 ', '2916697 ', '22470 ', '189 ', '520 ', '826 ', '2279 ', '28764 ', '7107 ', '288000 ', '9800 ', '4760 ', '72 ', '1450 ', '170 ', '1984 ', '2955 ', '65532 ', '65919 ', '2111 ', '3810 ', '18 ', '244 ', '104 ', '139 ', '360177 ', '36733 ', '4480 ', '165474 ', '1985 ', '10000 ', '232 ', '150 ', '11 ', '14057567 ', '8760 ', '48 ', '6321 ', '3150 ', '17256 ', '187 ', '399 ', '14 ', '467 ', '597 ', '23700 ', '615 ', '6819 ', '1000 ', ' ', '2633 ', '200 ', '13028 ', '800 ', '1700 ', '521 ', '120000 ', '666 ', '88 ', '200 ', '2279 ', '23570 ', '10000 ', '37700 ', '1850 ', '11 ', '147270 ', '3150 ', '17256 ', '597 ', '7624 ', '314 ', '1197 ', '70 ', '7624 ', '26737 ', '10000 ', '13611 ', '12684 ', '48 ', '731 ', '731 ', '557 ', '107 ', '158716 ', '15744 ', '153000 ', '557 ', '36 ', '4200 ', '61069 ', '52417 ', '900 ', '35040 ', '4746 ', '73 ', '11000 ', '4465 ', '145 ', '202 ', '221 ', '597 ', '298 ', '110341 ', '705 ', '2101 ', '1765 ', '150 ', '4000 ', '6272 ', '1996 ', '35040 ', '75840 ', '400 ', '1014 ', '10129 ', '4000 ']

In [214]:
#scrape No of attribute
attribute=[]
try:
    attributes=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')
    for x in attributes:
        attribute.append(x.text)
except NoSuchElementException:
    attribute.append('-')
except StaleElementReferenceException:
    attribute.append('-')
attribute=attribute[1:]#first row is title of table 'No of Attribute'
print(len(attribute),attribute)

622 ['8 ', '14 ', '38 ', '294 ', '279 ', '7 ', ' ', '69 ', '8 ', '26 ', '1 ', '4 ', '4 ', '9 ', '10 ', '34 ', '32 ', '13 ', '6 ', '14 ', '22 ', '36 ', '6 ', ' ', '6 ', '42 ', '15 ', ' ', '9 ', '9 ', '54 ', '39 ', '33 ', '20 ', ' ', ' ', ' ', '12 ', '8 ', '30 ', ' ', '10 ', '3 ', '5 ', '75 ', '19 ', '27 ', ' ', '19 ', '1558 ', '34 ', '4 ', '617 ', '12 ', '16 ', '7 ', '4 ', '16 ', '7 ', ' ', '56 ', '18 ', '8 ', '22 ', ' ', '58 ', ' ', '61 ', '7 ', ' ', '649 ', '22 ', '168 ', '168 ', '8 ', ' ', '10 ', '64 ', '16 ', '8 ', '17 ', ' ', ' ', '72 ', '4 ', '6 ', '10 ', '35 ', '35 ', '4 ', '102 ', '57 ', '22 ', '44 ', '45 ', ' ', ' ', '5 ', '9 ', '21 ', '32 ', '17 ', '16 ', '38 ', '21 ', '40 ', '13 ', '8 ', '17 ', ' ', ' ', '15 ', '22 ', '68 ', '40 ', '17 ', '89 ', ' ', '4 ', '12 ', ' ', ' ', '86 ', '72 ', '61 ', '12 ', '481 ', '42 ', ' ', ' ', ' ', ' ', ' ', ' ', '5 ', '90 ', ' ', '5 ', ' ', ' ', '14 ', '20 ', '13 ', '36 ', '19 ', '9 ', '18 ', '4 ', '60 ', '10 ', ' ', ' ', '10 ', '4 ', '3 ', '11 ', '11 ', ' ', '6 ', '13 ', ' ', '100000 ', '9 ', '101 ', '10000 ', '20000 ', '100000 ', '5000 ', '500 ', '73 ', '43 ', '23 ', '3 ', '5 ', ' ', '256 ', '591 ', '70 ', '91 ', '10 ', '128 ', '6 ', '12 ', '3231961 ', '5409 ', '26 ', ' ', ' ', '10 ', '23 ', '24 ', '13 ', '8 ', ' ', '27 ', '50 ', '90 ', '138672 ', ' ', '386 ', ' ', ' ', '12 ', '147 ', '6 ', '8 ', '27 ', '10000 ', '20000 ', '10000 ', '54877 ', '4702 ', '24 ', '29 ', '17 ', '3 ', '128 ', '10 ', '242 ', '120 ', ' ', '4 ', '13 ', '52 ', '47 ', '857 ', '9 ', '7 ', '200 ', '4 ', ' ', '561 ', '64 ', '8 ', '7 ', '10 ', '9 ', '4 ', '8 ', '77 ', '51 ', '18 ', '1950000 ', '18 ', '1300 ', '41 ', '6 ', '5625 ', '5 ', ' ', '7 ', '33 ', '5 ', '15 ', '9 ', '19 ', '5 ', '5 ', '1000000 ', '129 ', ' ', '20 ', '152 ', '24 ', '16 ', '35 ', '17 ', '5 ', '18 ', '28 ', '7 ', '309 ', '3 ', '6 ', ' ', ' ', '16 ', '13 ', '5 ', '6 ', '8 ', '2 ', '4 ', '148 ', '55 ', '17 ', '8 ', '42 ', '26 ', '50 ', '2 ', '281 ', '120 ', ' ', '6 ', '120432 ', '150000 ', '529 ', ' ', '16 ', '2500 ', '5 ', '68 ', '16 ', '100 ', '216 ', '23 ', '33 ', '140256 ', '19 ', '20 ', '20 ', '49 ', '12 ', '30 ', '5232 ', '20 ', '1 ', ' ', '61 ', '27 ', '53 ', '11 ', '25 ', '0 ', '20 ', '9 ', '3 ', '561 ', '82 ', '13 ', '16 ', '13 ', '28 ', '4 ', ' ', '24 ', '34 ', '8 ', '128 ', '15 ', '513 ', '7 ', '7 ', '5 ', '15 ', '480000 ', '11 ', '54 ', '561 ', '64 ', '6 ', '116 ', '19 ', ' ', '5812 ', '9 ', '32 ', '29 ', '67 ', ' ', '25 ', '6400 ', '10 ', '5 ', '13 ', '98 ', '36 ', '69 ', '2158859 ', '518 ', '15 ', '179 ', ' ', '12 ', '38 ', '65 ', '102 ', '86 ', '7 ', '53 ', '20 ', '1 ', '71 ', '29 ', '20531 ', '65 ', '3 ', '22 ', '38 ', '22 ', '4814 ', '698 ', '13 ', '10 ', '59 ', '56 ', '482 ', '171 ', '5 ', '500 ', '411 ', '8519 ', '21 ', '21 ', '171 ', '7 ', '49 ', '12 ', '3 ', '21 ', '9 ', '8 ', '7 ', '2 ', '11 ', '11 ', '173 ', '5 ', '15 ', '3 ', '105 ', '25000 ', ' ', '18 ', '21000 ', '115 ', '21 ', '206 ', '43680 ', '8 ', '10 ', '59 ', '10 ', '5 ', '5 ', '1000 ', '138 ', ' ', '16 ', '2 ', '10 ', ' ', '8 ', '6 ', '129 ', '81 ', '12 ', '6 ', '22 ', '18 ', '9 ', '754 ', '14 ', '5 ', ' ', ' ', '18 ', '7 ', '7 ', ' ', '7 ', '5 ', '6 ', '4 ', '18 ', '11 ', '25 ', ' ', '20 ', '12 ', '46 ', '9 ', '8 ', '49 ', '11 ', '8 ', '54 ', '36 ', '3916 ', '710 ', '18 ', '8 ', '29 ', '7 ', '9 ', '37 ', '6 ', '1024 ', '1024 ', '14 ', '7 ', '8265 ', '29 ', '25 ', '3 ', '115 ', '1 ', '12 ', '13 ', '200000 ', '6 ', '21 ', '4 ', '2400 ', '175 ', '10 ', '4714 ', '23 ', '17 ', '2 ', '9 ', '8 ', '280 ', '49 ', '3 ', '14 ', '19 ', ' ', '54 ', '8 ', '1087 ', '12 ', '3 ', '17 ', '8 ', '9 ', '12 ', '1656 ', '6 ', '2 ', '11 ', '533 ', '14 ', '84 ', '22 ', '16 ', '52 ', '19 ', '3 ', '14 ', '321 ', '13 ', '13 ', '55 ', '39 ', '4 ', '7 ', '79 ', '1 ', ' ', '14 ', '96 ', '21 ', ' ', '5 ', '2 ', '69 ', '9 ', '124 ', '20 ', '25 ', '11 ', '19 ', '9 ', '9 ', '5 ', '7 ', '4006 ', '2 ', '19 ', '4 ', '13 ', '55 ', '1 ', '7842 ', '15 ', '15 ', '70 ', '7842 ', '4 ', '14 ', '17 ', '23 ', '321 ', '1068 ', '1068 ', '5 ', '6 ', '4 ', ' ', '5 ', '5 ', '15 ', '7 ', '21 ', '9 ', '8 ', '11 ', '21 ', '22 ', '2 ', '241 ', '33 ', '29 ', '7 ', '1 ', ' ', '4 ', '11 ', '47 ', '10 ', '3 ', '2 ', '632 ', '6826 ', '11 ', '525 ', '50 ', '7 ', '16 ', '2 ']

In [213]:
#scrape year
year=[]
try:
    years=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
    for x in years:
        year.append(x.text)
except NoSuchElementException:
    year.append('-')
except StaleElementReferenceException:
    year.append('-')
year=year[1:]#first row is title of table 'No of Instances'
print(len(year),year)

622 ['1995 ', '1996 ', ' ', '1998 ', '1998 ', '1992 ', '1987 ', '1992 ', '1993 ', '1987 ', '1994 ', '1994 ', ' ', '1988 ', '1992 ', '1995 ', '1995 ', '1990 ', '1997 ', '1996 ', '1988 ', '1989 ', '1994 ', ' ', ' ', '1995 ', ' ', '1992 ', '1987 ', '1997 ', '1998 ', '1995 ', '1998 ', ' ', ' ', '1994 ', ' ', '1989 ', '1996 ', '1990 ', '1990 ', '1987 ', '1999 ', '1989 ', '1988 ', '1988 ', '1989 ', ' ', '1990 ', '1998 ', '1989 ', '1988 ', '1994 ', '1990 ', '1988 ', '1988 ', '1990 ', '1991 ', '1990 ', ' ', '1992 ', '1988 ', '1990 ', '1996 ', '1995 ', '1990 ', ' ', '1992 ', '1992 ', '1994 ', ' ', '1987 ', '1994 ', '1994 ', '1997 ', '1991 ', '1995 ', '1998 ', '1998 ', '1993 ', '1988 ', ' ', ' ', '1992 ', '1993 ', '1988 ', '1989 ', '1988 ', '1987 ', '1993 ', '1988 ', '1999 ', '2001 ', '2001 ', ' ', '1992 ', '1993 ', '1997 ', '1991 ', '1987 ', '1994 ', '1988 ', '1987 ', '1993 ', '1988 ', '1988 ', '1991 ', '1996 ', '1990 ', ' ', '1999 ', '1999 ', '2002 ', ' ', '2000 ', '1999 ', '1999 ', '2001 ', '1999 ', '1999 ', '2000 ', '1999 ', '2000 ', '1999 ', '1999 ', ' ', '1998 ', '1999 ', '2001 ', '1999 ', ' ', '2003 ', '1999 ', '1999 ', '1997 ', '1999 ', '1999 ', '1998 ', ' ', ' ', ' ', '1994 ', ' ', '1993 ', '1990 ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '1989 ', '2006 ', '2006 ', '2007 ', '2007 ', '2007 ', '2007 ', '2008 ', '2008 ', '2008 ', '2007 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2009 ', '2008 ', '2008 ', '2008 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2010 ', '2009 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2014 ', '2013 ', '2013 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2015 ', '2014 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2016 ', '2017 ', '2016 ', '2017 ', '2017 ', '2016 ', '2016 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2018 ', '2018 ', '2016 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ']

In [215]:
#make dataframe
df=pd.DataFrame()
df['Dataset name']=name
df['Data type']=data
df['Task']=task
df['Attribute type']=attribute_type
df['No of instances']=instance
df['No of attribute']=attribute
df['Year']=year
df

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [217]:
#close driver
driver.close()